### ISSUE TITLE
[Bug] BCEWithLogitsLoss Import Error

### ISSUE THREAD

**Issue by kvah** [facebookresearch/CrypTen#161]
Hi there,

The docstring for BCEWithLogitsLoss has escape characters (\t and \r) that prevent the function from being imported properly. I believe converting the docstring to a raw string should fix the issue.

![image](https://user-images.githubusercontent.com/38406600/87837206-8d796d80-c847-11ea-8de9-e1a6431dd552.png)

**Comment by knottb** [comment]
This should be fixed now. Closing this issue.
