### ISSUE TITLE
Tutorial Training SMPC on GPU with multiple workers

### ISSUE THREAD

**Issue by jlevy44** [facebookresearch/CrypTen#177]
Hi there! Thanks for adding GPU support. Can you add a tutorial or two on developing a SMPC training algorithm which utilizes CUDA? 

I seem to be having difficulties with getting such an algorithm up and running. So far, when I spawn multiple workers to load the private datasets, I can't load my model to cuda because it is in a forked subprocess (eg. https://github.com/pytorch/pytorch/issues/40403), which I tried to circumvent using https://pytorch.org/docs/stable/notes/multiprocessing.html#cuda-in-multiprocessing , however, this seems to cause pickling errors.

Thanks!

https://github.com/OpenMined/PySyft/issues/4561

**Comment by jlevy44** [comment]
https://github.com/OpenMined/PySyft/blob/44dd09d944ab4f927a1e35a6a1e623265cd6cb11/examples/experimental/CrypTen/CrypTen%20-%20Training%20an%20Encrypted%20Neural%20Network%20across%20Workers%20using%20Jails.ipynb

**Comment by knottb** [comment]
This seems to be an issue with forking subprocesses. Are you able to switch your multiprocessing start method to spawn?

**Comment by jlevy44** [comment]
Yes, I am doing that, and it solves the gpu problem but other problems arise. when I do this, I seem to have issues with pickling my Other functions (Eg. training model or even loading the data into a shared party) as per the decorator and Distributed launcher. I’ve been trying both out.
