### ISSUE TITLE
[BUG] mpc_autograd_cnn throws a TypeError

### ISSUE THREAD

**Issue by jayavanth** [facebookresearch/CrypTen#178]
## Environment
OS: MacOS 10.15.6
Python: Python 3.7.6

## Commit Head
6dec17c9078946f2c1cbd9c8a0af8a08aabf880e

## Requirement versions
crypten==0.1
torch==1.6.0
torchvision==0.5.0
visdom==0.1.8.9
numpy==1.18.1
onnx==1.7.0

## Command
`$  python mpc_autograd_cnn/launcher.py`

## Output
[output](https://pastebin.com/1368Ssqq)

**Comment by gmuraru** [comment]
Could you try the fix from here? https://github.com/facebookresearch/CrypTen/pull/179

**Comment by jayavanth** [comment]
@gmuraru Yes that worked!
