### ISSUE TITLE
Issues with mathematical operations

### ISSUE THREAD

**Issue by RTajeddine** [facebookresearch/CrypTen#180]
Hello, I am having issues with the math operations. I have small numbers in my code, and I am having incorrect results when I multiply, divide, do the square or the square root of the numbers. I tried changing precision but that did not help. Then I tested on simple examples, and it seems that these operations give incorrect results for high or low numbers.
I also noticed that making the precision higher makes the products and divisions give wrong outputs, even for integers.
Would there be a good way to avoid these issues?

**Comment by lvdmaaten** [comment]
Can you post a minimal repro of your issue? That will help us investigate the issue you are seeing.

In general, small numerical errors are to be expected in CrypTen because it uses 16-bit fixed-point computations (by default). You can increase the precision but this can have adverse effects as well. In particular, it increases the probability of wrap-around errors when performing division by a public value. The probability of such an error occurring scales linearly in the number of precision bits. Note that each multiplication involves a public division as well (to divide out the multiplier used to generate the fixed-point encoding). We will post a detailed description of all protocols implemented in CrypTen as well as of issues like this in the next few days. You may be seeing such wrap-around errors when you increase the precision?

Computing square-roots (and certain powers) is done by computing a logarithm and exponential. Those are computed using Householder and limit approximations, respectively. You can try to improve the quality of those approximations by changing the `log_iterations`, `log_exp_iterations`, and `exp_iterations` attributes in `MPCConfig` from their default values.

**Comment by RTajeddine** [comment]
Hi, thank you for your response. Here is a very simple example of the issue. My problem is that I need a higher precision that 16 bits, but then most of the calculations become invalid. As you can see, even simple products give wrong results (division has the same issue).
Also, as you can see in the examples, even when I set the precision to 16 (the default), it still has a problem doing the square root of 324 (I am okay with the minor inaccuracies, but when it gives a "junk" value, it is hard to deal with it.
<img width="732" alt="Screenshot 2020-10-07 at 20 07 07" src="https://user-images.githubusercontent.com/51314648/95364517-97a48880-08d9-11eb-8dd8-b30786371508.png">
<img width="1001" alt="Screenshot 2020-10-07 at 20 09 29" src="https://user-images.githubusercontent.com/51314648/95364527-9bd0a600-08d9-11eb-89c1-a6a660fbe1a6.png">
<img width="984" alt="Screenshot 2020-10-07 at 20 08 39" src="https://user-images.githubusercontent.com/51314648/95364545-a12df080-08d9-11eb-9a61-62c55edfe1d2.png">



.

I did try changing the iterations, but that did not help either.

**Comment by lvdmaaten** [comment]
Thanks! Would you mind copy-pasting your code here? That will make it easier to run it myself as well :)

**Comment by RTajeddine** [comment]
Yes, sure.

`#!/usr/bin/python3

import torch
import crypten 

crypten.init()

crypten.encoder.set_default_precision(30)

import crypten.mpc as mpc
import crypten.communicator as comm 
from crypten.mpc import MPCTensor

@mpc.run_multiprocess(world_size=2)
def test():
	
	rank = comm.get().get_rank()

	mat1=MPCTensor([1.0,2.0,3.0])
	mat2=MPCTensor([2.0,4.0,6.0])

	mat=mat1*mat2
	matsquare=mat*mat
	
	print('mat1 = ', mat1.get_plain_text())
	print('mat2 = ', mat2.get_plain_text())
	print('mat = ', mat.get_plain_text())
	print('mat^2 = ', matsquare.get_plain_text())
	print('Square root of mat^2 = ', matsquare.sqrt(log_iterations=10).get_plain_text())


test()`

**Comment by lvdmaaten** [comment]
I think that using a precision this high is very risky: it substantially increases the probability of seeing a wrap-around error in a public division, after which your results are essentially garbage (see my comment above).

We evaluate `x.sqrt()` by computing `x.log().mul(0.5).exp()`. The logarithm is computed via modified Householder iterations. By default, we use 8-th order iterations; these are reasonable accurate when `x` is in the range `[0.0001, 250]`. In your example, the largest value of `x` is beyond that range (`3 * 6 * 3 * 6 = 324`). You can increase the range of `x` values that is supported by the `log` function by increasing the order of the iterations. 

The following code:
```
#!/usr/bin/python3

import crypten
import crypten.communicator as comm
import crypten.mpc as mpc
from crypten.mpc import MPCTensor


crypten.init()
crypten.encoder.set_default_precision(16)
crypten.mpc.config.log_order = 12
crypten.mpc.config.log_exp_iterations = 12
crypten.mpc.config.exp_iterations = 12


@mpc.run_multiprocess(world_size=2)
def test():

    rank = comm.get().get_rank()
    print(f"rank = {rank}")

    mat1 = MPCTensor([1.0, 2.0, 3.0])
    mat2 = MPCTensor([2.0, 4.0, 6.0])

    mat = mat1 * mat2
    matsquare = mat * mat

    print("mat1 = ", mat1.get_plain_text())
    print("mat2 = ", mat2.get_plain_text())
    print("mat = ", mat.get_plain_text())
    print("mat^2 = ", matsquare.get_plain_text())
    print("Square root of mat^2 = ", matsquare.sqrt().get_plain_text())


test()
```
outputs:
```
rank = 0
rank = 1
mat1 =  tensor([1., 2., 3.])
mat1 =  tensor([1., 2., 3.])
mat2 =  tensor([2., 4., 6.])
mat2 =  tensor([2., 4., 6.])
mat =  tensor([ 2.,  8., 18.])
mat =  tensor([ 2.,  8., 18.])
mat^2 =  tensor([  4.,  64., 324.])
mat^2 =  tensor([  4.,  64., 324.])
Square root of mat^2 =  tensor([ 1.9845,  8.3844, 18.0236])
Square root of mat^2 =  tensor([ 1.9845,  8.3844, 18.0236])
```
which is not too bad.

Note that it is very difficult to get these types of approximations to work well on very large domains, so you generally have to be much more mindful of numerical issues when working with CrypTen than with PyTorch. We are working on tooling that will make it easier for users to debug these kinds of numerical problems.

**Comment by RTajeddine** [comment]
Thank you. Is there a way to at least detect when I am getting garbage values? I mean, my issue is that I am dealing with a wide range of numbers, and I need a higher precision than 16, I am fine with 20 or 24, however, even products and divisions start giving bad values, as you stated above. I am trying to be very careful to reduce errors, but it seems whatever I do, I am still running into issues with the results. 
I can not really lower my precision, so I wonder if there is at least a way, in code, to detect that the value is garbage so I could at least ignore it, instead of having it ruin the whole program.

**Comment by lvdmaaten** [comment]
@knottb is working on tooling that will help users detect wrap-around and numerical issues during debugging. We will hope to have an update on that soon.

However, please note there is no silver bullet that solves all numerical problems. As a CrypTen user, you are always going to have to think carefully about how to set up the computation in a way that prevents numerical issues. (This is true in PyTorch as well; for example, a user needs to make sure to not run code like `torch.exp(torch.tensor([100.]))`.)
