### ISSUE TITLE
Tutorial 3 cannot load examples.<anything>

### ISSUE THREAD

**Issue by SuperElectron** [facebookresearch/CrypTen#181]
Going through the tutorial, I cannot download anything from the 'examples' module.
- I have completed the Tutorials 0-2, and just ran into this issue for some reason (I haven't left my computer since starting).
- I have attached a pdf of the jupyter notebook, and a screen shot of the error.

![tutorial_3_errror](https://user-images.githubusercontent.com/11896926/95387495-a2ddc100-08a5-11eb-9841-c3a36555408c.png)

[Tutorial_3_Introduction_to_Access_Control - Jupyter Notebook.pdf](https://github.com/facebookresearch/CrypTen/files/5343788/Tutorial_3_Introduction_to_Access_Control.-.Jupyter.Notebook.pdf)

Any tips to get this going?  What did I miss or is missing in documentation?
Thanks in advance!!

**Comment by gmuraru** [comment]
You can try setting the ```PYTHON_PATH``` like this
```PYTHON_PATH=$(pwd)/${PYTHON_PATH```
Where **pwd** - should be the root of the CrypTen project

**Comment by SuperElectron** [comment]
![error](https://user-images.githubusercontent.com/11896926/95388441-2815a580-08a7-11eb-8075-e7f81b95afd7.png)

**Comment by SuperElectron** [comment]
I get the same results for this: 
```
!export PYTHON_PATH=$(pwd)/${PYTHON_PATH}
!echo $PYTHON_PATH
```

**Comment by gmuraru** [comment]
Put this in the terminal before launching the notebook server

**Comment by SuperElectron** [comment]
I'll get back later, I can't take the server down right now because other's are working on it.  Thanks for now :)

**Comment by lvdmaaten** [comment]
@SuperElectron Were you able to get this to work?

**Comment by gmuraru** [comment]
Ping @SuperElectron

**Comment by SuperElectron** [comment]
ah such a late reply! I left it alone

**Comment by akkolwalkar** [comment]
I have followed everything mentioned here and still getting the same issue.

**Comment by knottb** [comment]
This should have been addressed by https://github.com/facebookresearch/CrypTen/pull/216. Closing.
