### ISSUE TITLE
RuntimeError: result type Float can't be cast to the desired output type Long

### ISSUE THREAD

**Issue by superxii** [facebookresearch/CrypTen#207]
While I was running the Tutorial_4 in jupyter (https://github.com/facebookresearch/CrypTen/blob/master/tutorials/Tutorial_4_Classification_with_Encrypted_Neural_Networks.ipynb)
, it was fine until the part with Classifying Encrypted Data with Encrypted Model.
```
import crypten.mpc as mpc
import crypten.communicator as comm

labels = torch.load('/tmp/bob_test_labels.pth').long()
count = 100 # For illustration purposes, we'll use only 100 samples for classification

@mpc.run_multiprocess(world_size=2)
def encrypt_model_and_data():
    # Load pre-trained model to Alice
    model = crypten.load('models/tutorial4_alice_model.pth', dummy_model=dummy_model, src=ALICE)
    
    # Encrypt model from Alice 
    dummy_input = torch.empty((1, 784))
    private_model = crypten.nn.from_pytorch(model, dummy_input)
    private_model.encrypt(src=ALICE)
    
    # Load data to Bob
    data_enc = crypten.load('/tmp/bob_test.pth', src=BOB)
    data_enc2 = data_enc[:count]
    data_flatten = data_enc2.flatten(start_dim=1)

    # Classify the encrypted data
    private_model.eval()
    output_enc = private_model(data_flatten)
    
    # Compute the accuracy
    output = output_enc.get_plain_text()
    accuracy = compute_accuracy(output, labels[:count])
    print("\tAccuracy: {0:.4f}".format(accuracy.item()))
    
encrypt_model_and_data()
```
When I ran that part,an Error occured: `(RuntimeError: result type Float can't be cast to the desired output type Long)` 

Environmental Setup: 
Conda 4.9.2
Cudatoolkit 11.0.221
Jupyter  1.0.0
Crypten 0.1

Step to reproduce the error:
By running the Tutorial_4 in jupyter and error will occur in the part "Classifying Encrypted Data with Encrypted Model"

The attachment document is the error log , conda env list and the HTML for the jupter with code.
[error.txt](https://github.com/facebookresearch/CrypTen/files/5824425/error.txt)
[condalist.txt](https://github.com/facebookresearch/CrypTen/files/5850250/condalist.txt)
[Tutorial_4_Classification_with_Encrypted_Neural_Networks.zip](https://github.com/facebookresearch/CrypTen/files/5850319/Tutorial_4_Classification_with_Encrypted_Neural_Networks.zip)

OS: Ubuntu 18.04
Display Card: 1070Ti

It would be great if there is help or  knowing the part(s) that go wrong, thanks!

**Comment by napoay** [comment]
+1

**Comment by knottb** [comment]
This tutorial has been updated to no longer have this issue. Closing issue.
