### ISSUE TITLE
Loading each party's data across machines.

### ISSUE THREAD

**Issue by chanfm81** [facebookresearch/CrypTen#208]
Hi,

Lets say Alice's data is already stored on '/tmp/alice_data.pth' on machine 1 and Bob's data is already stored on '/tmp/bob_data.pth' on machine 2. Assuming Alice is rank 0 and Bob is rank 1, the following code will fail for Alice on line for enc_bob_data :
```
rank = os.getenv('RANK')
print('rank ' + rank)

crypten.init()
torch.set_num_threads(1)

num_features = 2

torch.manual_seed(1)

alice_data = torch.randn(1, num_features)
print(alice_data)

ALICE = 0
BOB = 1

filenames = {
    "alice_data": "/tmp/alice_data.pth",
    "bob_data": "/tmp/bob_data.pth",
}

crypten.save(alice_data, filenames["alice_data"], src=ALICE)

@mpc.run_multiprocess(world_size=2)
def joint_compute():

    if comm.get().get_rank() == 0:
        enc_alice_data = crypten.load(filenames["alice_data"], src=ALICE)
    else:
        enc_bob_data = crypten.load(filenames["bob_data"], src=BOB)

    enc_total = enc_alice_data + enc_bob_data
    dec_out = enc_total.get_plain_text()
    print(dec_out)

joint_compute()
```

The 2 machines/parties are joined by:
```
INIT_METHOD = 'tcp://xxxx:23456'
current_env["RENDEZVOUS"] = INIT_METHOD
```

Any idea? Thanks.

**Comment by lvdmaaten** [comment]
In the example above, where is `"/tmp/bob_data.pth"` being written? Does that file actually exist when Bob is trying to load it? Unless the file already happens to exist prior, I would expect Bob to fail in your example when he tried to read the data.

What does the stack trace look like? In particular, how do you know that the error happens in Alice and not in Bob?

**Comment by chanfm81** [comment]
Hi, thanks for the reply.

"/tmp/bob_data.pth" is written on Bob's machine and does not exist on Alice's machine. 

My problem is how does Alice gets Bob's predefined data in the common MPC function? Maybe the MPC function is not written correctly. If so, do you have any pointers on that?

**Comment by lvdmaaten** [comment]
If you create a `CrypTensor` by doing `encrypted_tensor = crypten.cryptensor(plaintext_tensor, src=src_party_rank)` then the party with rank  `src_party_rank` will secretly share its data with the other parties. In this case, it is assumed that the other parties know the size of `plaintext_tensor` in advance. So the other parties must call the exact same function with a dummy `plaintext_tensor` input (which is ignored; only its size is used).

If the size of the tensor to be shared is not known in advance, you can run `encrypted_tensor = crypten.cryptensor(plaintext_tensor, src=src_party_rank, broadcast_size=True)`. This will first tell the other parties what the size of `plaintext_tensor` is, and then share it. So that way, the other parties don't need to know the size of tensors beforehand but create them dynamically. The other parties should also call the same function but for them, the `plaintext_tensor` can be anything (it is ignored entirely).

Does that answer your question?

**Comment by chanfm81** [comment]
Hi, thanks for the reply.

I have tried your suggestion but it does not seem to work.

Please see Alice's code below:
```
import os
import torch
import crypten
from crypten import mpc
import crypten.communicator as comm

print('MPC started ...')

crypten.init()
torch.set_num_threads(1)

rank = comm.get().get_rank()
print('rank = ' + str(rank))

world_size = comm.get().get_world_size()
print('world_size = ' + str(world_size))

# Set random seed for reproducibility
torch.manual_seed(1)

# Simulate Alice's data
input1 = torch.tensor(3)
input2 = torch.empty(input1.size())

ALICE = 0
BOB = 1

@mpc.run_multiprocess(world_size=2)
def joint_compute(input1,input2):
    print('joint_compute')

    x_enc = crypten.cryptensor(input1, src=0)
    y_enc = crypten.cryptensor(input2, src=1)

    enc_total = x_enc + y_enc
    dec_out = enc_total.get_plain_text()
    print('decrypted output = ' + str(dec_out))

joint_compute(input1,input2)
```

Please see Bob's code below:
```
import os
import torch
import crypten
from crypten import mpc
import crypten.communicator as comm

print('MPC started ...')

crypten.init()
torch.set_num_threads(1)

rank = comm.get().get_rank()
print('rank = ' + str(rank))

world_size = comm.get().get_world_size()
print('world_size = ' + str(world_size))

# Set random seed for reproducibility
torch.manual_seed(1)

# Simulate Bob's data
input2 = torch.tensor(5)
input1 = torch.empty(input2.size())

ALICE = 0
BOB = 1

@mpc.run_multiprocess(world_size=2)
def joint_compute(input1,input2):
    print('joint_compute')

    x_enc = crypten.cryptensor(input1, src=0)
    y_enc = crypten.cryptensor(input2, src=1)

    enc_total = x_enc + y_enc
    dec_out = enc_total.get_plain_text()
    print('decrypted output = ' + str(dec_out))

joint_compute(input1,input2)
```

Below is Alice's output:
```
MPC started ...
rank = 0
world_size = 2
joint_compute
joint_compute
decrypted output = tensor(-1.4074e+14)
decrypted output = tensor(-1.4074e+14)
```

Below is Bob's output:
```
MPC started ...
rank = 1
world_size = 2
joint_compute
joint_compute
decrypted output = tensor(5.)
decrypted output = tensor(5.)
```

Can you advise if i have missed out anything from above code snippet?

Thanks.
