### ISSUE TITLE
No grad after backward

### ISSUE THREAD

**Issue by yuanlics** [facebookresearch/CrypTen#210]
Hi,

I have been looking at customized CrypTen modules, but the backward seems easy to fail. Could you check if this is an issue?

```
x = torch.rand(2, 4)
x_enc = crypten.cryptensor(x, requires_grad=True)

# y_enc = x_enc    # This line gives the grad correctly
y_enc = x_enc[:]   # The question is how to allow indexing & slicing operations to have gradients?

grad = torch.rand_like(y_enc.get_plain_text())
grad_enc = crypten.cryptensor(grad)
y_enc.backward(grad_enc)
print(x_enc.grad.get_plain_text())
```

Also, I have been seeing `ValueError: CrypTen does not support op Mul.` quite often when calling `crypten.nn.from_pytorch`. May I ask why op Mul is not supported?

Thanks!

**Comment by lvdmaaten** [comment]
My guess that Python built-in indexing functions like `[:]` are not correctly handled in the autograd (they may accidentally detach the `CrypTensor` from the graph). Does using function calls for indexing and slicing resolve your issue? Functions like [`narrow`](https://github.com/facebookresearch/CrypTen/blob/master/crypten/gradients.py#L244), [`flatten`](https://github.com/facebookresearch/CrypTen/blob/master/crypten/gradients.py#L231), [`reshape`](https://github.com/facebookresearch/CrypTen/blob/master/crypten/gradients.py#L218), _etc._ should be working correctly.

Re `Mul`: I suppose we just need to add it [here](https://github.com/facebookresearch/CrypTen/blob/master/crypten/nn/module.py).

**Comment by yuanlics** [comment]
Hi,

Thanks for your advice on indexing. Now they work fine. 

However, I encountered another `crypten.nn.from_pytorch` issue. Here is the code to reproduce:

```
import torch
import crypten

crypten.init()

class Net(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        i = torch.tensor([0, 2, 5])
        y = torch.take(x, i)
#        y = x.take(i)  # also fails
        return y
    
    
model = Net()
x = torch.tensor([[4, 3, 5],
                  [6, 7, 8]])
ct_model = crypten.nn.from_pytorch(model, torch.empty_like(x))
```

The traceback:

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-11-fa230ba966c7> in <module>
     46 print(y, y.shape)
     47 
---> 48 ct_model = crypten.nn.from_pytorch(model, torch.empty_like(x))
     49 ct_model.encrypt()
     50 ct_model.train()

~/sfi/CrypTen/crypten/nn/onnx_converter.py in from_pytorch(pytorch_model, dummy_input)
     35     # construct CrypTen model:
     36     f = _from_pytorch_to_bytes(pytorch_model, dummy_input)
---> 37     crypten_model = from_onnx(f)
     38     f.close()
     39 

~/sfi/CrypTen/crypten/nn/onnx_converter.py in from_onnx(onnx_string_or_file)
    122     """Converts an onnx model to a CrypTen model"""
    123     converter = FromOnnx(onnx_string_or_file)
--> 124     crypten_model = converter.to_crypten()
    125     return crypten_model
    126 

~/sfi/CrypTen/crypten/nn/onnx_converter.py in to_crypten(self)
    175                 assert (
    176                     constant_module is not None
--> 177                 ), f"Pattern not supported: expected Constant shape before {crypten_class} node."
    178                 node_input_names.remove(constant_module[0])
    179                 attributes["shape"] = constant_module[1].value.long().tolist()

AssertionError: Pattern not supported: expected Constant shape before <class 'crypten.nn.module.Reshape'> node.
```

It is strange since `crypten.cryptensor.CrypTensor.take` works fine in a `crypten.nn.Module`. Could you check if this is an issue?

Thanks

**Comment by lvdmaaten** [comment]
The conversion of indexing operations from PyTorch via ONNX is challenging: it is difficult to tell from the ONNX graph whether or not indices should be encrypted or not. I will put out some PRs this week that should hopefully partly resolve this issue.

**Comment by lvdmaaten** [comment]
@yuanlics I have landed a [major overhaul](https://github.com/facebookresearch/CrypTen/commit/3d02c23aba74930d4335e57a00712bb0d020abc8) of how the importing from PyTorch works that should address a whole host of issues like the one you are addressing. Can you please check whether these changes resolved your issue?
