### ISSUE TITLE
Getting Started with SMPC (Error!)

### ISSUE THREAD

**Issue by akkolwalkar** [facebookresearch/CrypTen#214]
I am a newbie to Crypten and SMPC, I was trying to play around with the library.

```
import crypten
import torch
crypten.init() 
torch.set_num_threads(1)
import torchvision.datasets as datasets
import torchvision.models as models
import torchvision.transforms as transforms
transform=transforms.ToTensor()
trainset = datasets.MNIST(root='./data', train=True,download=True, transform=transform)from torchvision.models import resnet18
from torch import nn
model = resnet18(num_classes=10) # MNIST has 10 classesencrypted_model=crypten.nn.from_pytorch(model,trainset[0])
```

I get the following error
`RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. `

How to debug this?

**Comment by knottb** [comment]
I've found that this can happen with certain versions of dependencies (in particular, I've found that Python >3.7 can cause issues). I've found that with a fresh conda environment, the following should enable the tutorials to work properly:

```
conda install python==3.7.0
pip install crypten

conda install jupyter
```

I'll note that there are still some remaining bugs in the tutorials. We have fixes for all of them coming in pull requests and should land soon.
