### ISSUE TITLE
Add LogSoftmax, Softmax, and Dropout modules

### ISSUE THREAD

**Issue by shreyansh26** [facebookresearch/CrypTen#22]
I have used a pytorch VGG-16 pre-trained model, added 2 more layers to it to fit my needs and trained the model and saved it as a `.pth` file.
However, when I am trying to convert it to a CrypTen model using the `.load()` function. It gives the following error
```
<ipython-input-41-8acf3ddeab54> in <module>()
      1 dummy_model = dummy_model
----> 2 plaintext_model = crypten.load('/content/drive/My Drive/vgg16-model.pth', dummy_model=dummy_model, src=ALICE)
      3 
      4 # Encrypt the model from Alice:
      5 

/usr/local/lib/python3.6/dist-packages/crypten/__init__.py in load(f, encrypted, dummy_model, src, **kwargs)
    233 
    234                 # raise error
--> 235                 raise TypeError("Unrecognized load type %s" % type(result))
    236 
    237         # Non-source party

TypeError: Unrecognized load type <class 'dict'>
```
I saw in the `crypten/__init__.py` file that this error is in the block where it is checked whether **result** which is the return value of `torch.load(f, **kwargs)`, is of type *tensor* or *torch.nn.Module* and this error is raised when it is neither of them.

So to check, I ran the `result =  torch.load(f, **kwargs)` command separately and that gave the following error - 
```
AttributeError                            Traceback (most recent call last)

/usr/local/lib/python3.6/dist-packages/torch/serialization.py in _check_seekable(f)
    190     try:
--> 191         f.seek(f.tell())
    192         return True

5 frames

AttributeError: 'VGG' object has no attribute 'seek'


During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)

/usr/local/lib/python3.6/dist-packages/torch/serialization.py in raise_err_msg(patterns, e)
    185                                 " Please pre-load the data into a buffer like io.BytesIO and" +
    186                                 " try to load from it instead.")
--> 187                 raise type(e)(msg)
    188         raise e
    189 

AttributeError: 'VGG' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
```

Is there any way to solve this issue so that I can use CrypTen with my pre-trained VGG-16 model?

**Comment by lvdmaaten** [comment]
What is the value of `type(torch.load('/content/drive/My Drive/vgg16-model.pth'))`? Is the VGG model wrapped in some other Python native type like a `dict` or something like that?

The reason I am asking is that [PyTorch's `VGG` extends `torch.nn.Module`](https://github.com/pytorch/vision/blob/master/torchvision/models/vgg.py#L24), which means that one would expect [this `if` statement to pass](https://github.com/facebookresearch/CrypTen/blob/master/crypten/__init__.py#L213). But looking at your stack trace, apparently, `result` is not a `torch.nn.Module` for some reason.

**Comment by shreyansh26** [comment]
Yes, sorry I should have updated the issue. I had tried `type(torch.load('/content/drive/My Drive/vgg16-model.pth'))` and it was actually a python `dict`. Something like - 
```
{'class_to_idx': {'NORMAL': 0, 'PNEUMONIA': 1}, 'classifier': Sequential(
   (0): Linear(in_features=25088, out_features=4096, bias=True)
   (1): ReLU(inplace=True)
   (2): Dropout(p=0.5, inplace=False)
   (3): Linear(in_features=4096, out_features=4096, bias=True)
   (4): ReLU(inplace=True)
   (5): Dropout(p=0.5, inplace=False)
   (6): Sequential(
     (0): Linear(in_features=4096, out_features=256, bias=True)
     (1): ReLU()
     (2): Dropout(p=0.2, inplace=False)
     (3): Linear(in_features=256, out_features=2, bias=True)
     (4): LogSoftmax()
   )
 ), 'epochs': 10, 'idx_to_class': {0: 'NORMAL',
  1: 'PNEUMONIA'}, 'optimizer': Adam (
 Parameter Group 0
     amsgrad: False
     betas: (0.9, 0.999)
     eps: 1e-08
     lr: 0.001
     weight_decay: 0
 ), 'optimizer_state_dict': {'param_groups': [{'amsgrad': False,
    'betas': (0.9, 0.999),
    'eps': 1e-08,
    'lr': 0.001,
    'params': [139841303849000,
     139841303849936,
     139841303849432,
     139841303849864,
     139841303849792,
     139841303849648,
     139841303849216,
     139841303848928,
     139841303850152,
     139841303850440,
     139841303850656,
     139841303850944,
     139841303847056,
     139841303850728,
     139841303850584,
     139841303850872,
     139841303850224,
     139841303851872,
     139841303852448,
     139841303852592,
     139841303852808,
     139841303852880,
     139841303852952,
     139841303852736,
     139841303852664,
     139841303852520,
     139841303853096,
     139841303853528,
     139841303853600,
     139841303853456,
     139841302912960,
     139841302912744,
     139841302912600,
     139841302912528],
    'weight_decay': 0}],
  'state': {139841302912528: {'exp_avg': tensor([-0.0029,  0.0029], device='cuda:0'),
    'exp_avg_sq': tensor([0.0005, 0.0005], device='cuda:0'),
    'step': 410},
   139841302912600: {'exp_avg': tensor([[-8.7793e-03,  8.4601e-03,  6.2012e-04,  1.1900e-16,  5.1145e-04,
              1.3293e-03, -8.4745e-06, -1.3452e-03, -3.2242e-03, -2.6280e-04,
             -3.4370e-03,  2.6770e-22,  1.2205e-22,  1.9747e-10, -1.1010e-08,
             -1.9576e-03, -6.6984e-03, -8.9865e-03,  2.2696e-05, -5.0271e-03,
              3.3309e-03,  4.2975e-22,  3.2065e-03,  6.3844e-19,  4.0227e-04,
              2.9525e-22,  4.6557e-04,  1.6030e-05,  2.4986e-06, -1.4930e-04,
             -9.3415e-06,  6.6601e-22,  8.6497e-22, -1.2222e-02,  9.5443e-22,
              1.0489e-03,  6.3559e-05,  2.4820e-19,  3.7591e-03,  1.7326e-10,
              7.1339e-04,  6.4981e-04,  1.3323e-07, -8.7584e-03,  6.0828e-22,
              3.2936e-22,  4.8026e-22,  8.6604e-03, -6.1743e-03,  3.7261e-04,
              .....
```
But I found that as given in the [tutorial notebook #4](https://github.com/facebookresearch/CrypTen/blob/master/tutorials/Tutorial_4_Classification_with_Encrypted_Neural_Networks.ipynb) if I don't use the `crypten.load()` for the time being (just as a hack) and load my model using a custom load method, and directly pass it to the `private_model = crypten.nn.from_pytorch(custom_loaded_model, dummy_input)`, then it gives the following error -
```
/usr/local/lib/python3.6/dist-packages/crypten/nn/__init__.py in from_onnx(onnx_string_or_file)
    159         # get operator type:
    160         if node.op_type not in ONNX_TO_CRYPTEN:
--> 161             raise ValueError("CrypTen does not support op %s." % node.op_type)
    162         cls = ONNX_TO_CRYPTEN[node.op_type]
    163 

ValueError: CrypTen does not support op LogSoftmax.
```
which I guess is because Softmax has yet not been implemented in this module since it is new. I am dealing with a classification problem and the softmax layer is actually required for it. So, this seems like a dead-end for now. Not sure how to proceed.

**Comment by lvdmaaten** [comment]
Got it. We need to add a `LogSoftMax` module [here](https://github.com/facebookresearch/CrypTen/blob/master/crypten/nn/module.py) for this to work.

In our examples, we trained directly using `CrossEntropyLoss` so the models did not need a `(Log)Softmax` module. As a temporary work-around, you could remove the `LogSoftmax` from your model and operate directly on the (encrypted) logit values. I hope there are no other operators that are still missing (I am a little surprised that it is not complaining about the `Dropout` layers, since I don't think we currently have support for those).

**Comment by noobyogi0010** [comment]
Hi @lvdmaaten !
I would like to add the **Softmax** module.
Thanks.

**Comment by vshobha** [comment]
Hi @noobyogi0010 Thanks, that would be great! Do you plan to add the missing Dropout module as well?

**Comment by shreyansh26** [comment]
Alright, thanks @lvdmaaten for the work-around you suggested, I guess I could try that.

**Comment by noobyogi0010** [comment]
@vshobha For now I've plan to work on Softmax module, once that is done, then I'll try the Dropout module.

**Comment by vshobha** [comment]
@noobyogi0010 thanks! I can also work on the Dropout (and/or Logsoftmax modules) in parallel -- happy either way -- just let me know!

**Comment by Yugandhartripathi** [comment]
@noobyogi0010 are you still working on it?

**Comment by vshobha** [comment]
The Dropout, Softmax and LogSoftmax modules have been added, and their descriptions are available in the documentation. https://crypten.readthedocs.io/
