### ISSUE TITLE
B2A needs to be run in parallel

### ISSUE THREAD

**Issue by vincehong** [facebookresearch/CrypTen#23]
https://github.com/facebookresearch/CrypTen/blob/master/crypten/mpc/primitives/converters.py#L35

    for i in range(bits):
        binary_bit = binary_tensor & 1
        arithmetic_bit = beaver.B2A_single_bit(binary_bit)

If we are to convert a full 64 bit B share into A share, this would cost 64x round trips, which is inefficient. The loop bodies have no dependency with each other, so they should be run in parallel.

**Comment by knottb** [comment]
Yes, that is correct. Because all of our current use of B2A only converts a single bit, we haven't put much effort into optimizing this. It shouldn't be too difficult to parallelize this.

Thanks for pointing this out.

**Comment by knottb** [comment]
This issue should be resolved by #24 . Closing this issue.
