### ISSUE TITLE
pytorch compatibility

### ISSUE THREAD

**Issue by culurciello** [facebookresearch/CrypTen#245]
Hi all, great project and thank you for this.

I was wondering if there is beta support for PyTorch 1.8 or above, and if it is planned.

I notice the test in front page works, but it is 2x off.

Thanks a lot

**Comment by lvdmaaten** [comment]
Hi Eugenio! 

I see no reason CrypTen would not work with PyTorch 1.8, but maybe I'm missing something. You mean the simple example in the `README.md` produces incorrect results? Is this with the source version of CrypTen or with the `pip` version? I just ran it with the `pip` version of CrypTen and PyTorch 1.8.1 and the results appear correct (`sum_xy_dec = tensor([3., 5., 7.])`).

**Comment by culurciello** [comment]
For some reason the one below does not work for me, but yes your example in front page is actually correct.
--
x = torch.rand(3,3)
y = torch.rand(3,3)

# encrypt:
x_enc = crypten.cryptensor(x)
y_enc = crypten.cryptensor(y)

# decrypt:
x_dec = x_enc.get_plain_text()

print('Input tensors:', x, y)
print('Enc. x tensor:', x_enc)
print('Dec. x tensor:', x_dec)
# print(x_enc._tensor)

# add encrypted tensors and decrypt sum:
sum_xy = x_enc + y_enc
sum_xy_dec = sum_xy.get_plain_text()
print('Example sum x+y:', sum_xy_dec)
print('Error: x+y - x_enc+y_enc', (x+y) - sum_xy_dec )

**Comment by culurciello** [comment]
Looks like I have installed an older version - will close
