### ISSUE TITLE
 semi-honest or dishonest majority?

### ISSUE THREAD

**Issue by carlzhangweiwen** [facebookresearch/CrypTen#25]
I found the paper link on the [document of Crypten](https://crypten.readthedocs.io/en/latest/mpctensor.html). As follows.
>For technical details see Damgard et al. 2012 and Beaver 1991 outlining the Beaver protocol used in our implementation.

SPDZ( Damgard et al. 2012) is dishonest majority. While, CrypTen is  semi-honest or dishonest majority?

**Comment by vincehong** [comment]
Currently CrypTen is semi-honest 3PC with honest majority.  The triple producer must not collude with Alice or Bob.

**Comment by knottb** [comment]
CrypTen also does not currently support Message Authentication Codes (MACs) which SPDZ uses to provide dishonest majority. We plan to include these at some point in the future, but do not currently have a timeline for this.
