### ISSUE TITLE
CUDALongTensor initializations default to using device "cuda"

### ISSUE THREAD

**Issue by kernelmethod** [facebookresearch/CrypTen#250]
Hi there --

I've found that in a few different cases, `CUDALongTensor` gets automatically initialized to use `device="cuda"` (which, at least for me, appears to be equivalent to `device="cuda:0"`). This can cause a few unexpected errors in situations where you're using a different GPU. For instance:

```
>>> import torch, crypten
>>> crypten.init()
>>> x = crypten.cryptensor(torch.randn(3, device="cuda:1"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/CrypTen/crypten/__init__.py", line 167, in cryptensor
    return __CRYPTENSOR_TYPES__[cryptensor_type](*args, **kwargs)
  File "/tmp/CrypTen/crypten/mpc/mpc.py", line 146, in __init__
    self._tensor = tensor_type(tensor=tensor, device=device, *args, **kwargs)
  File "/tmp/CrypTen/crypten/mpc/primitives/arithmetic.py", line 105, in __init__
    self.share += tensor
  File "/tmp/CrypTen/crypten/cuda/cuda_tensor.py", line 366, in __iadd__
    self._tensor += y
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!
```

In this case, the error occurs because a `CUDALongTensor` is initialized in `generate_random_ring_element` without setting a device:

https://github.com/facebookresearch/CrypTen/blob/3fe0e96632558d1210401c01d32ae8130f674c61/crypten/common/rng.py#L17-L18

... which, if you look at the `CUDALongTensor` code, causes it to default to using `"cuda"`:

https://github.com/facebookresearch/CrypTen/blob/3fe0e96632558d1210401c01d32ae8130f674c61/crypten/cuda/cuda_tensor.py#L64

Another example: if you patch `generate_random_ring_element` to use the device set in `**kwargs`, you get the same error if you do `x + x`:

```
>>> x + x
Traceback (most recent call last):
-- snip --
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!
```

In this case, the error occurs because `x.__add__` calls `x.clone`, which also creates a new `CUDALongTensor` without explicitly setting the device:

https://github.com/facebookresearch/CrypTen/blob/3fe0e96632558d1210401c01d32ae8130f674c61/crypten/cuda/cuda_tensor.py#L149

**Comment by lvdmaaten** [comment]
Thanks for reporting! 

My first thought is that the behavior of `CUDALongTensor` is probably correct: if `device` is not specified in the `CUDALongTensor` constructor, then defaulting to device `"cuda"` probably makes sense. What this means is that we need to be much more careful when creating new `CUDALongTensor`s though. 

In the first example, I presume the fix is to simply use the `device` that is input into `generate_random_ring_element()` as input into the `CUDALongTensor` constructor.

I am not sure I understand what is happening in the second example:

https://github.com/facebookresearch/CrypTen/blob/3fe0e96632558d1210401c01d32ae8130f674c61/crypten/cuda/cuda_tensor.py#L149-L150

Doesn't the `clone()` on the underlying PyTorch `CudaTensor` create a clone on the same device? Note that `CUDALongTensor` does not maintain its own device attribute -- the device is simply a `@property` that is taken from the underlying PyTorch tensor.

**Comment by kernelmethod** [comment]
Thanks for the reply!

> if device is not specified in the CUDALongTensor constructor, then defaulting to device "cuda" probably makes sense.

This makes sense to me. I think it might've been more precise for me to say that the default is good, it's just that there are a lot of cases where either

- a device is provided but `CUDALongTensor` doesn't get initialized with it (which is what happens with `generate_random_ring_element()` -- you just have to pass `device=str(kwargs["device"])`, assuming that argument is present), or
- a new `CUDALongTensor` is somehow derived from another tensor, but we don't use the device of the "parent" tensor (which seems to be happening with `shallow_copy()` -- see below)

and in those cases we end up reverting to the default.

> Doesn't the `clone()` on the underlying PyTorch `CudaTensor` create a clone on the same device?

Apologies -- yes, you're right. I should've paid a bit better attention to the error that I got. First, here's the stack trace after fixing `generate_random_ring_element()` (since I'd previously omitted it):

```
>>> import torch, crypten
>>> crypten.init()
>>> x = crypten.cryptensor(torch.randn(3, device="cuda:1"))
>>> x + x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/CrypTen/crypten/cryptensor.py", line 379, in __add__
    return self.add(tensor)
  File "/tmp/CrypTen/crypten/cryptensor.py", line 299, in autograd_forward
    result = grad_fn.forward(ctx, *args, **kwargs)
  File "/tmp/CrypTen/crypten/gradients.py", line 627, in forward
    return input.add(other)
  File "/tmp/CrypTen/crypten/mpc/mpc.py", line 54, in convert_wrapper
    return func(result, *args, **kwargs)
  File "/tmp/CrypTen/crypten/mpc/mpc.py", line 1263, in ob_wrapper_function
    result._tensor = getattr(result._tensor, name)(value, *args, **kwargs)
  File "/tmp/CrypTen/crypten/mpc/primitives/arithmetic.py", line 355, in add
    return self._arithmetic_function(y, "add")
  File "/tmp/CrypTen/crypten/mpc/primitives/arithmetic.py", line 326, in _arithmetic_function
    result.share = getattr(result.share, op)(y.share)
  File "/tmp/CrypTen/crypten/cuda/cuda_tensor.py", line 601, in regular_func
    result._tensor = getattr(result._tensor, func_name)(*args, **kwargs)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!
```

From the last two lines of the stack trace, I believe that where the error is actually occurring here is in `CUDALongTensor.add` (not `__add__`):

```
$ git diff crypten/cuda/cuda_tensor.py
diff --git a/crypten/cuda/cuda_tensor.py b/crypten/cuda/cuda_tensor.py
index cc66834..568eefd 100644
--- a/crypten/cuda/cuda_tensor.py
+++ b/crypten/cuda/cuda_tensor.py
@@ -593,12 +593,16 @@ def _add_regular_function(func_name):
     """
 
     def regular_func(self, *args, **kwargs):
+        print(f"Calling {func_name} with {args=}, {kwargs=}")
+        print(str(self.device))
         result = self.shallow_copy()
+        print(str(result.device))
         args = [t.tensor() if hasattr(t, "tensor") else t for t in args]
         for key, value in kwargs.items():
             if hasattr(value, "tensor"):
                 kwargs[key] = value.tensor()
         result._tensor = getattr(result._tensor, func_name)(*args, **kwargs)
+        print(f"Leaving {func_name}")
         return result
 
     setattr(CUDALongTensor, func_name, regular_func)
$ python3 test.py
Calling add with args=(CUDALongTensor(tensor([ 15401, -40245, -75123], device='cuda:1')),), kwargs={}
cuda:1
cuda:0
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    x + x
-- same stack trace as before --
  File "/tmp/CrypTen/crypten/cuda/cuda_tensor.py", line 604, in regular_func
    result._tensor = getattr(result._tensor, func_name)(*args, **kwargs)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!
```

... so my impression from this is that in this particular case it's actually `CUDALongTensor.shallow_copy` causing the issue in this particular example.

**Comment by kernelmethod** [comment]
Here's that fix to `crypten/common/rng.py` I've been using to get past the issues with `generate_random_ring_element()`:

```
$ git diff rng.py
diff --git a/crypten/common/rng.py b/crypten/common/rng.py
index 3bf5da8..72fa231 100644
--- a/crypten/common/rng.py
+++ b/crypten/common/rng.py
@@ -15,7 +15,9 @@ def generate_random_ring_element(size, ring_size=(2 ** 64), **kwargs):
         -(ring_size // 2), (ring_size - 1) // 2, size, dtype=torch.long, **kwargs
     )
     if rand_element.is_cuda:
-        return CUDALongTensor(rand_element)
+        device = kwargs.get("device")
+        device = str(device) if device is not None else None
+        return CUDALongTensor(rand_element, device=device)
     return rand_element
 
 
@@ -27,5 +29,7 @@ def generate_kbit_random_tensor(size, bitlength=None, **kwargs):
         return generate_random_ring_element(size, **kwargs)
     rand_tensor = torch.randint(0, 2 ** bitlength, size, dtype=torch.long, **kwargs)
     if rand_tensor.is_cuda:
-        return CUDALongTensor(rand_tensor)
+        device = kwargs.get("device")
+        device = str(device) if device is not None else None
+        return CUDALongTensor(rand_tensor, device=device)
     return rand_tensor
```
