### ISSUE TITLE
How to create a quantization model from the encrypted model

### ISSUE THREAD

**Issue by amyzx** [facebookresearch/CrypTen#277]
Hi, I am trying to quantize the encrypted model in Tutorial 4. I define the following class and hope to use Post Training (Static) Quantization in pytorch. 
However, the encrypted model has many layers and cannot be loaded into the AliceNet_Quant. Could you give me some suggestions about how to create a uint8 quantizated model? Thanks!
 
 
![image](https://user-images.githubusercontent.com/8285571/123413172-07cc7900-d5e5-11eb-8adf-5708e8114b61.png)

**Comment by knottb** [comment]
Interesting. In theory, this shouldn't be affected by the quantization since all values (weights, inputs, etc.) are encoded to a fixed-point encoding when encrypted. 

In practice, what may be happening is the line layers `QuantStub()` and `DeQuantStub()` do not have analogs in ONNX for the conversion.  If you want to convert the model, you can remove these layers before the conversion - it will be the same in either case since all encoding in CrypTen is converted to int64 due to the encryption protocol.

**Comment by amyzx** [comment]
@knottb  Thanks for your detailed reply! 
In fact, I have a situation where a server **S** holds a model, and a client **C** has data. They could use CrypTen to do inference on encrypted data and encrypted model.

However, **C** may still concerns about whether **S** carries out inference correctly. A malicious **S** may change its model by modifying weights or changing model structures. I am not sure whether the changes of encrypted model can be detected by **C**.

In my current implementation, I am trying to use zkSNARK (a zero-knowledge technique) to prove the correctness of model inference. I quantize a plaintext floating model to a uint8 model by using the plaintext data. Then I use [ark-snark](https://github.com/arkworks-rs/snark) to verify every step of inference computation. Using zkSNARK can ensure the correctness of the inference procedure. 

Now I hope to combine my code with CrypTen to protect the privacy of **C**'s data and **S**'s model. I find the encrypted model weights are not the same as original one. If I save the encrypted model's `state_dict` and load it to a quantization model (`AliceNet_Quant` without `QuantStub()` and `DeQuantStub()` ), I get the following error.

`'ArithmeticSharedTensor' object has no attribute 'shape'`

Could you give me any suggestion about how to implement my situation? Currently, I am trying to learn about the details of encrypted inference procedure in CrypTen, and hope to convert the encrypted model to a quantization format which can be used in zkSNARK.

**Comment by knottb** [comment]
I see. So it may be possible to perform inference this way - but the implementation details are a bit unclear. In particular, CrypTen uses 16-bit fixed-point encoding by default (i.e. all inputs are converted to 16-bit fixed-point). You may be able to modify the encoding to what you want by setting default precision to 0 bits (i.e. integers). Currently this can be done using `crypten.encoder.set_default_precision(0)`, though the API for this is changing pretty soon to use a `config.yaml` file to configure.

Without a stack trace, I can't tell what is causing your AttributeError, however it can be fixed easily by adding a `shape` attribute:

```
@property
def shape(self):
    return self._tensor.shape
```

inside of `crypten/mpc/primitives/arithmetic.py` inside of the `ArithmeticSharedTensor` class.

Let me know if this helps.

**Comment by amyzx** [comment]
@knottb Thanks a lot! I will have a try.

**Comment by MccRee177** [comment]
@amyzx Thanks a lot for bringing this problem. I am trying to follow up one of my previous paper([ICLR 2023](https://openreview.net/forum?id=CWmvjOEhgH-)) by trying quantization on MPC. Do you mind sharing the status on this? I also have my email address in the Github page if you are interested!

**Comment by amyzx** [comment]
@MccRee177  Hi, I find that the encrypted model in CrypTen is already quantizated (although it's an int64 model).

Actually, I just want a uint8 model because I follow the work in [ZEN](https://github.com/UCSB-TDS/ZEN). But later I find in rust we can use i64 to process the encrypted model from CrypTen. 

We don't need to do any modifications in my scene. I just use the encrypted model in CrypTen as an int64 quantizated model.
