### ISSUE TITLE
Fully Homomorphic Encryption

### ISSUE THREAD

**Issue by DreamingRaven** [facebookresearch/CrypTen#28]
##  Feature
The ability to fully homomorphically encrypt tensors, be able to store them/ serialize and reload the encrypted data. unencrypt the data (in particular for databases), and compute operations using GPU parallelisation or in a distributed manner.

## Alternatives

Secure multiparty computation, and differential privacy. However neither of these fulfill the need for trustless systems, or systems that involve a non-tech-savy but sensitive data source. Or the long term availability of encrypted data without risk to the data owner(s).

## Additional context

There are multiple FHE libraries out there such as HeLib, and MS-SEAL. However they all require rather hacky integration with either pytorch or tensorflow (although TensorFlow 1 is the only one that I have seen working with FHE thus far). I read that there was an aspiration to eventually integrate FHE into CrypTen, is this still the case? I just wanted to formalise an issue for FHE, because it is something I would be very interested in if it were to be implemented. However that being said I am more than up for helping out with pull requests if the opportunity so arises as it would be great to see here.

**Comment by knottb** [comment]
Hi,

We do have FHE as an item on our roadmap, but do not have a release timeframe in mind. If you have a specific use-case or feature suggestion (i.e. specific protocol or functionality that would be helpful), we may be able to include it in a quicker timeframe. We are always interested in collaborating with the community and welcome Pull Requests - Please let us know if you are still interested.

Thanks

**Comment by DreamingRaven** [comment]
Hey knottb, I am indeed interested in collaborating to bring FHE to pytorch/CrypTen however due to constraints at this time I am unable to do so, however if the opportunity arises I will see what I can do. Also please let me know if and when you guys plan on delving into this more so that I can potentially help out.

**Comment by Geremia** [comment]
@DreamingRaven Any update on this?
