### ISSUE TITLE
Don't duplicate torch.serialization logic in crypten.common.serial

### ISSUE THREAD

**Issue by ezyang** [facebookresearch/CrypTen#281]
I had to do some manual porting of changes in https://github.com/pytorch/pytorch/pull/59671 and it's probably not going to be the last time we do it.

Mercifully, reapplying the changes was relatively easy, but I'm not sure how many versions of PyTorch crypten supports and we may have to goop it up again to make it portable if you guys are targeting multiple versions. Would have been easier if there was just no duplication at all.

IIUC, the crypten serializer is just doing the restricted pickling for safety, right? Maybe we can add that functionality to pytorch directly.

cc @knottb (who helped me debug my fix patch)

**Comment by knottb** [comment]
Yes, that is correct. We are using restricted pickling for security reasons (in particular to restrict arbitrary code execution via the unpickling process). We include a whitelist of "safe classes" that are acceptable for unpickling that users can add to via registration (e.g. for custom nn modules).

**Comment by ezyang** [comment]
Restricted pickling is something that others have requested. I'll see what I can do.
