### ISSUE TITLE
How to compute the cosine similarity between two cryptensors?

### ISSUE THREAD

**Issue by Sylarair** [facebookresearch/CrypTen#284]
##  Feature

I wonder how to compute the cosine similarity between two cryptensors. Could anyone give me some suggestions?

For example,
```
import crypten

x = torch.tensor([1, 2, 3], dtype = torch.float)
x_enc = crypten.cryptensor(x)

y_enc = crypten.cryptensor([2.0, 3.0, 4.0])
```

**Comment by knottb** [comment]
We can address this as a feature request. Shouldn't be too involved as all of the intermediate steps are implemented:

```
def cosine_similarity(x, y):
    dot = x.dot(y)
    inv_norms = x.square().sum().mul(y.square().sum()).inv_sqrt()
    return dot.mul(inv_norms)
```

**Comment by lvdmaaten** [comment]
@knottb Note that PyTorch implementation [does something to prevent division by zero](https://pytorch.org/docs/stable/generated/torch.nn.CosineSimilarity.html). We may need something similar if we were to add cosine similarity in CrypTen.

**Comment by knottb** [comment]
Actually, this epsilon for numerical precision only matters when the reciprocal of the norms is very small (product is less than 1e-8), which means the norms are large (product is at least 1e8). If our norms are this large, then the inverse square root will fail. Currently our precision allows for inputs up to around [0.05, 200] (it may be useful to work on improving this).
<img width="752" alt="Screen Shot 2021-07-08 at 3 17 49 PM" src="https://user-images.githubusercontent.com/19143914/124978391-b4542500-dfff-11eb-9a6e-4a14fa3c0dff.png">

**Comment by Sylarair** [comment]
Thanks! So is there no existing packages for such computation?

**Comment by knottb** [comment]
We have written one since this issue was opened - It should be landed soon, but is waiting on some earlier PRs to land. For now, you can use the implementation I provided, but we've completed the implementation so it should be supported with full testing / autograd support shortly.

**Comment by knottb** [comment]
This feature has been pushed, closing this issue.

**Comment by hobbitlzy** [comment]
> Actually, this epsilon for numerical precision only matters when the reciprocal of the norms is very small (product is less than 1e-8), which means the norms are large (product is at least 1e8). If our norms are this large, then the inverse square root will fail. Currently our precision allows for inputs up to around [0.05, 200] (it may be useful to work on improving this). <img alt="Screen Shot 2021-07-08 at 3 17 49 PM" width="752" src="https://user-images.githubusercontent.com/19143914/124978391-b4542500-dfff-11eb-9a6e-4a14fa3c0dff.png">

Hi, what if the data is beyond the valid range [0.05,200]? Is there any way to compute them correctly now?
