### ISSUE TITLE
run on multiple machine

### ISSUE THREAD

**Issue by veryhannibal** [facebookresearch/CrypTen#289]
I have read the tutorial_6 CrypTen on AWS instances. I want to know what do i need to do if I want run it on several machines with Ubuntu system. Just like what I need to do on aws? Thanks.

**Comment by knottb** [comment]
Should work the same. The main thing that needs to be configured is the communication between machines. This can be done by setting environment variables pursuant to https://pytorch.org/docs/stable/distributed.html. (Environment variables that should be set are:
```
{
    "WORLD_SIZE": world_size,
    "RANK": rank,
    "BACKEND", backend,
    "RENDEZVOUS": init_method,
}
```

It is possible you also need to set the `MASTER_ADDR` environment variable.

**Comment by veryhannibal** [comment]
Thanks, may you please give more tutorials with details about running Crypten on multiple machines?

**Comment by veryhannibal** [comment]
If I want to assign Alice and Bob to different ports respectively on same machine, how can I modify the code? My you give me some suggestion?
