### ISSUE TITLE
pip install crypten

### ISSUE THREAD

**Issue by YZY010203** [facebookresearch/CrypTen#292]
when I execute "pip install crypten",it will automatically install torch-1.4.0 at the same time,but the requirements.txt requires torch>1.7.0.When I run the code in readme.md,it will report an error like this picture.How to solve this problem? 
![图片](https://user-images.githubusercontent.com/63569612/128819213-e91543f0-cda7-4279-adbe-c225d68f7c6c.png)

**Comment by knottb** [comment]
What version of PyTorch are you using? It is possible that some features in our codebase use attributes that are deprecated in the latest versions of PyTorch.

**Comment by knottb** [comment]
Closing as this should be fixed in newest crypten distribution.
