### ISSUE TITLE
Large Float Division without ConfigManager("reciprocal_nr_iters",12)

### ISSUE THREAD

**Issue by anmolagarwalcp810** [facebookresearch/CrypTen#300]
Earlier we had trained model with ConfigManager("reciprocal_nr_iters",12) to take care of accurately dividing with large numbers.
But since ConfigManager() has now been removed, is there any other to take care of large divisions?

Thanks in advance.

**Comment by knottb** [comment]
There are two ways to change this setting now:

1. You can change this permanently by editing [configs/default.yaml](https://github.com/facebookresearch/CrypTen/blob/master/configs/default.yaml) or supplying your own config file.

2. You can use `crypten.config.temp_override({"functions. reciprocal_nr_iters": 12})` as you would use `ConfigManager`.


We will edit the documentation to reflect this.

**Comment by anmolagarwalcp810** [comment]
Thanks a lot for clarifying.
