### ISSUE TITLE
Bug on Zeroes Multiplication

### ISSUE THREAD

**Issue by anmolagarwalcp810** [facebookresearch/CrypTen#308]
On multiplying two zero tensors from source 0 in 5 party setting, I was getting large +/- values (4.2950e+09). I have also attached the jupyter notebook containing the code and requirements.txt file containing dependencies information.

[Jupyter Notebook](https://github.com/anmolagarwalcp810/Jupyter_Notebooks/blob/main/Issue_zeroes_multiplication.ipynb)

Python: 3.7.11
[Dependencies](https://github.com/anmolagarwalcp810/Jupyter_Notebooks/blob/main/requirements.txt)

Please help. Thanks in advance.

**Comment by knottb** [comment]
Thanks for pointing this out. I am able to reproduce this. This only happens in the 3+ party setting implying it may be a result of the division protocol. However, I'm not sure why this would happen in this case. Looking into it now.

**Comment by knottb** [comment]
This should be fixed in https://github.com/facebookresearch/CrypTen/pull/313. Closing this issue.

**Comment by anmolagarwalcp810** [comment]
Thanks a lot for fixing the issue!
