### ISSUE TITLE
when release the next version of CrypTen?

### ISSUE THREAD

**Issue by haoranhe** [facebookresearch/CrypTen#309]
Thanks for your team's work on privacy perserving machine learning. I want know when release the next version of CrypTen, because the latest version 0.1 cannot support the sigmoid function, but I really need it to model a logistic regression in my domain.

**Comment by lvdmaaten** [comment]
We plan to update the CrypTen version on PiPy shortly. In the meantime, can you install CrypTen from source? The current Github version of CrypTen has support for sigmoidal functions.

**Comment by lvdmaaten** [comment]
We just released a new version (0.4.0) of CrypTen: https://pypi.org/project/crypten/

This version supports sigmoidal functions.
