### ISSUE TITLE
Question about the running time of ReLU and Conv

### ISSUE THREAD

**Issue by ziqi-zhang** [facebookresearch/CrypTen#311]
Hi, I want to use Crypten for secure inference involved by the data owner and the model owner (ie the fourth scenario ``model hiding'' in the tutorial 3). I noticed that several recent papers focus to improve the running time of activation function (eg ReLU), such as [SAFENET](https://openreview.net/forum?id=Cz3dbFm5u-), [DeepReDuce](https://arxiv.org/abs/2103.01396) and [DELPHI](https://www.usenix.org/conference/usenixsecurity20/presentation/mishra). 

I evaluate the running time of crypted models and found that the time spent by ReLU is very short. The major time cost is the computation of convolution layers. So I was wondering if the technique of Crypten different from the previously mentioned papers? Because for my understanding, both Crypten and those papers are similar because they all perform computation on the encrypted data and neither of the party can learn the information of the other party. Is my understanding inaccurate?

Best Wishes,

**Comment by lvdmaaten** [comment]
Please refer to Section C.1.4 of the [CrypTen white paper](https://arxiv.org/pdf/2109.00984.pdf) for details on how ReLU activation functions are implemented. Essentially, we rely on conversion from arithmetic to binary secret shares (and vice versa) to compare the input `x` with zero, and compute the ReLU activation function based on that. This is a fairly standard protocol, so I wouldn't expect CrypTen to be much faster here than other implementations.

**Comment by ljjsalt** [comment]
@lvdmaaten I observed the same situation as Ziqi said. Most of the time are spent on Linear operations. Is this because the Crypten's implementation of Linear operations are slower(like not optimized for matrix multiplication) or paper like Delphi moved the inference time from online to offline?

**Comment by ljjsalt** [comment]
Hi @ziqi-zhang, did you finally figure out why the time spent on ReLUs are less then you expected?
