### ISSUE TITLE
What's the difference between save/load and save_from_party/load_from_party?

### ISSUE THREAD

**Issue by steven0301** [facebookresearch/CrypTen#319]
Hi, I'm trying to do some test with **Tutorial_3_Introduction_To_Access_Control.ipynb** and I have some questions.
It seems that save function can save both plain and encrypted data while save_from_party can only get plain data as an input.
When I brought data using load() & get_plain_text(), I wasn't able to get plain data, but when I tried using load_from_party() & get_plain_text(), it revealed data which I think should be kept private.
It would be really appreciate if you tell me how it is possible to get data revealed with load_from_party function, the difference between two functions and when should I use each function to build application.
Thank you.

**Comment by knottb** [comment]
`save()` and `load()` are intended to be used with `CrypTensor` inputs and save as multiple files (one per party) which each contain a share of the encrypted value. `save_from_party()` and `load_from_party()` are intended to load a PyTorch `Tensor` from a single source, then perform all necessary steps to encrypt tensor. This functionality circumvents the need for large blocks of code each time we want to load data that is held by one source (e.g. blocks of code has if-else blocks for different functionality on each party which transmits / receives sizes of tensors and encrypts).
