### ISSUE TITLE
Pycon-workshop-2020 error

### ISSUE THREAD

**Issue by rtaiello** [facebookresearch/CrypTen#328]
Hi all,

when I run `python3 training_across_parties.py` ( I previously executed `pip install -r requirements.txt` ), I get the following error: 
**File "/Users/riccardo/projects/CrypTen/pycon-workshop-2020/training_across_parties.py", line 43, in encrypt_digits
    crypten.save(images, "/tmp/data/alice_images.pth", src=ALICE)
...
TypeError: save() got an unexpected keyword argument 'src'**

I got the same error both on macOS and Linux.

Thanks in advance

**Comment by knottb** [comment]
I believe the function template for `save()` has changed since then since the `src` argument is not used. I will fix this in the PyCon-workshop-2020 notebook, but if you are interested in running this in the meantime, you can just remove the `src` argument and the rest should work as expected.

**Comment by knottb** [comment]
Closing as this has been fixed in a landed PR.
