### ISSUE TITLE
mpc.run_multiprocess decorated functions blocking

### ISSUE THREAD

**Issue by youben11** [facebookresearch/CrypTen#33]
When going through tutorial 3 and 4, cells 6 and 7 respectively blocks (waited for around 1 hour without results), the run_multiprocessor function is waiting for child processes [here](https://github.com/youben11/CrypTen/blob/master/crypten/mpc/context.py#L91). I guess something is going wrong with a child process but couldn't figure out what yet.

### Workspace
- python 3.7.5
- torch 1.3.0
- crypten is installed from the last commit
- Linux MANJARO

**Comment by vshobha** [comment]
Hi. I noticed that you submitted a PR for Tutorial 7... were you able to successfully run the mpc.run_multiprocess decorated functions in Tutorial 7?

**Comment by vreis** [comment]
Thanks for trying out CrypTen, @youben11! 
As @vshobha mentioned, we are having trouble reproducing your issue. I have two requests:
1. Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

2. Please run `pip freeze` in your conda environment and paste here the output.

Thanks a lot!

**Comment by youben11** [comment]
@vshobha the mpc.run_multiprocess decorated functions in Tutorial 7 (cell 4) blocks, one of the child (or all) processes doesn't exit.

@vreis below are information you requested:

```bash
$ python collect_env.py
Collecting environment information...
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Manjaro Linux
GCC version: (GCC) 9.2.0
CMake version: version 3.16.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.0
[pip3] torch==1.3.1
[conda] torch                     1.3.0                    pypi_0    pypi
[conda] torchvision               0.4.1                    pypi_0    pypi
$
$ pip freeze
absl-py==0.9.0
astor==0.8.1
attrs==19.3.0
backcall==0.1.0
bleach==3.1.0
certifi==2019.11.28
Click==7.0
-e git+https://github.com/facebookresearch/CrypTen.git@3306b42644814fd4f8a1c29e3cc1ec8673e77b79#egg=crypten
decorator==4.4.1
defusedxml==0.6.0
entrypoints==0.3
Flask==1.1.1
Flask-SocketIO==4.2.1
future==0.18.2
gast==0.2.2
google-pasta==0.1.8
grpcio==1.26.0
h5py==2.10.0
importlib-metadata==1.3.0
ipykernel==5.1.3
ipython==7.10.2
ipython-genutils==0.2.0
ipywidgets==7.5.1
itsdangerous==1.1.0
jedi==0.15.1
Jinja2==2.10.3
joblib==0.14.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.0.0
jupyter-core==4.6.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
lz4==2.2.1
Markdown==3.1.1
MarkupSafe==1.1.1
mistune==0.8.4
more-itertools==8.0.2
msgpack==0.6.2
nbconvert==5.6.1
nbformat==4.4.0
notebook==6.0.2
numpy==1.18.0
onnx==1.6.0
opt-einsum==3.1.0
pandocfilters==1.4.2
parso==0.5.2
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.2.1
prometheus-client==0.7.1
prompt-toolkit==2.0.9
protobuf==3.11.2
ptyprocess==0.6.0
Pygments==2.5.2
pyrsistent==0.15.6
python-dateutil==2.8.1
python-engineio==3.11.1
python-socketio==4.4.0
PyYAML==5.2
pyzmq==18.1.0
qtconsole==4.6.0
scikit-learn==0.22
scipy==1.4.1
Send2Trash==1.5.0
six==1.13.0
sklearn==0.0
syft==0.2.0a2
tblib==1.6.0
tensorboard==1.15.0
tensorflow==1.15.0
tensorflow-estimator==1.15.1
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
tf-encrypted==0.5.9
torch==1.3.0
torchvision==0.4.1
tornado==6.0.3
traitlets==4.3.3
typing-extensions==3.7.4.1
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.56.0
websockets==8.1
Werkzeug==0.16.0
widgetsnbextension==3.5.1
wrapt==1.11.2
zipp==0.6.0
zstd==1.4.3.2
```

**Comment by QinZihao00** [comment]
Exactly same issues here. Cells 6 in tutorial 3 and cell 7 in tutorial 4.

**Comment by vreis** [comment]
@youben11: thanks for the information! @vshobha was able to reproduce your issue, we're fixing it in https://github.com/facebookresearch/CrypTen/pull/37 . Let me know if that works for you!

@QinZihao00: can you please try out https://github.com/facebookresearch/CrypTen/pull/37 and see if that fixes the issue for you as well? Thanks!

**Comment by vreis** [comment]
Also FYI we're landing https://github.com/facebookresearch/CrypTen/pull/37 right now, so maybe just wait a bit and re-test on master -- no need to cherry-pick the fix.

**Comment by youben11** [comment]
Thank you @vreis @vshobha, it's working fine now.
