### ISSUE TITLE
Training on shuffle input

### ISSUE THREAD

**Issue by personwhofloat** [facebookresearch/CrypTen#346]
Hi, I have a problem with training a CrypTen model. In the original code, each iteration has data sampled in increasing order (from start to end). It is working well. However, when I try the same code running on shuffle indices (i.e. shuffle the dataset to get random samples), loss value is strangely large.
The following code is working (with normal loss):
```
...
normal_idx = list(range(50))
X = X[normal_idx]
y = y[normal_idx]
...
```
But the modified code is not working:
```
...
random_idx = random.sample(range(X.shape[0]),50)
X = X[random_idx]
y = y[random_idx]
...
```
Loss function behavior: (1st example)
```
epoch 0 loss: 2.2911529541015625
epoch 0 loss: 2.2911529541015625
epoch 1 loss: 2.19610595703125
epoch 1 loss: 2.19610595703125
epoch 2 loss: 2.1101837158203125
epoch 2 loss: 2.1101837158203125
epoch 3 loss: 2.0311126708984375
epoch 3 loss: 2.0311126708984375
epoch 4 loss: 1.957763671875
epoch 4 loss: 1.957763671875
epoch 5 loss: 1.88861083984375
epoch 5 loss: 1.88861083984375
epoch 6 loss: 1.8235321044921875
epoch 6 loss: 1.8235321044921875
epoch 7 loss: 1.761566162109375
epoch 7 loss: 1.761566162109375
epoch 8 loss: 1.7025299072265625
epoch 8 loss: 1.7025299072265625
epoch 9 loss: 1.645843505859375
epoch 9 loss: 1.645843505859375
```

2nd example:
```
epoch 0 loss: -67078296.0
epoch 0 loss: -67078296.0
epoch 1 loss: -16226049.0
epoch 1 loss: -16226049.0
epoch 2 loss: -1518386560.0
epoch 2 loss: -1518386560.0
epoch 3 loss: 677972608.0
epoch 3 loss: 677972608.0
epoch 4 loss: -421613856.0
epoch 4 loss: -421613856.0
epoch 5 loss: -325339104.0
epoch 5 loss: -325339104.0
epoch 6 loss: 838485056.0
epoch 6 loss: 838485056.0
epoch 7 loss: -753985472.0
epoch 7 loss: -753985472.0
epoch 8 loss: -61582872.0
epoch 8 loss: -61582872.0
epoch 9 loss: -6656207.5
epoch 9 loss: -6656207.5
```

```

**Comment by knottb** [comment]
The most obvious thing potential issue is that the line `random_idx = random.sample(...)` will cause shuffles to be different across parties. In certain cases this won't matter, but if data is not coordinated across parties, you will get issues that look like this. This will always happen if you are indexing after encryption. E.g.:

```
random_idx = random.sample(...)

# This will always break
X = crypten.cryptensor(x, src=SRC)
X_sampled = X[random_idx]

# This may not break
x_sampled = x[random_idx]
X_sampled = crypten.cryptensor(x_sampled, src=SRC)
```

The better way to do this would be to coordinate your random samples across parties. This can be done either by hard-coding the random seed in your `random` module:

```
import random
random.seed(0)
```

Or, if you don't want to make your run deterministic by hard-coding a seed, you can communicated the random indexes:

```
random_idx = random.sample(...)
random_idx = crypten.communicator.get().broadcast_obj(random_idx, SRC)
```
