### ISSUE TITLE
How does the code run in mutiprocess?

### ISSUE THREAD

**Issue by Flyingbeanss** [facebookresearch/CrypTen#348]
In the Tutorial_3_Introduction_to_Access_Control's cell 7,
```
@mpc.run_multiprocess(world_size=2)
def feature_aggregation_example():
    """Apply feature aggregation access control model"""
    # Alice loads some features, Bob loads other features
    features_alice_enc = crypten.load_from_party(filenames["features_alice"], src=ALICE)
    features_bob_enc = crypten.load_from_party(filenames["features_bob"], src=BOB)
    
    # Concatenate features
    features_enc = crypten.cat([features_alice_enc, features_bob_enc], dim=0)
    
    # Encrypt labels
    labels_enc = crypten.cryptensor(labels)
    
    # Execute training
    w, b = train_linear_svm(features_enc, labels_enc, epochs=epochs, lr=lr)
    
    # Evaluate model
    evaluate_linear_svm(test_features, test_labels, w, b)
        
feature_aggregation_example()
```
I want to know the effect of the multiprocess.
Is the code just run when in the match process where has the args "src"?For example,when the process's rank is 0,it just run the src is ALICE's(ALICE=0) and do not run BOB's.But if it's true,why the training code just run for one time?Which rank does the output belong to?
Maybe this problem is easy,i just do not understand it and forgive my poor English please.

**Comment by knottb** [comment]
This works a little differently than you are thinking. The code for this is here: https://github.com/facebookresearch/CrypTen/blob/main/crypten/mpc/context.py#L45-L105

The way this works is as follows:

1. The parent process creates `world_size` new child processes using `multiprocessing.Process()`
2. All child processes connect using `crypten.init()`
3. Each child process runs the decorated function with the provided arguments and generates a return value
4. The parent process receives the return values from each child process and terminates all child processes
5. The parent process returns a list of all return values from the child processes.

These are pretty simple steps, but it allows us to mock a crypten process (with multiple parties) using only one machine. This allows us to test certain things easily, but may not reproduce 100% of the behavior of a true multiple machine run.

**Comment by Flyingbeanss** [comment]
Hi @knottb,I see it.Thank you for your reply!
