### ISSUE TITLE
Do you actually require pytest-runner during setup?

### ISSUE THREAD

**Issue by hmaarrfk** [facebookresearch/CrypTen#351]
https://github.com/facebookresearch/CrypTen/blob/c6e8ebfbb52c849e1fefee9b626340d6a4fa35dc/setup.py#L54

We are trying to add the package to conda and it seems weird to depend on pytest runner during the setup phase.

Is it actually a setup dependency? 

If not, can we remove it from the setup dependencies and add it to the test dependencies?

Thank you!

Best,

Mark

https://github.com/conda-forge/staged-recipes/pull/15720

**Comment by knottb** [comment]
I don't think we need this. I believe the setup.py file was written using setuptools, which seems to have deprecated this here: https://pypi.org/project/pytest-runner/

**Comment by hmaarrfk** [comment]
Thank you for confirming. That was our understanding as well.
