### ISSUE TITLE
How to use run_multiprocess decorator in a class

### ISSUE THREAD

**Issue by amyzx** [facebookresearch/CrypTen#359]
Hi, I have a class file which contains server functions including init(), compute() and so on.

How could I use this class file in crypten? I hope to run 2 processes which init its own class and call compute().  

If I just add run_multiprocess on compute(), it does not work well. 

In addition, I find some functions cannot use run_multiprocess decorator. It gives me an error message: 

_pickle.PicklingError: Can't pickle <XXX>: it's not the same object as XXX

Could you give me some suggestions about this situation? Thanks a lot!

**Comment by knottb** [comment]
I think the best way to do this would be to define the class without `run_multiprocess`. Then you would write a function to call inside of `run_multiprocess` that would initialize an instance of the class and call `compute()`. For example:


```
class ServerClass:
    def __init__(self, *args, **kwargs):
        pass
        
    def compute(self, *args, **kwargs):
        pass
 
 
 @mpc.run_multiprocess(world_size):
 def execute_computation():
     server = ServerClass(*args, **kwargs)
     server.compute(*args, **kwargs)
 
 
 execute_computation()
 ```

**Comment by amyzx** [comment]
Thanks a lot!
