### ISSUE TITLE
The `get_plain_text()` function essentially performs an all-reduce on the relevant tensor. This requires all the processes (except the TTP, if it exists) to participate in the communication, that is, all parties must agree to share their secret share of the tensor. If one party calls `get_plain_text()` but the other parties do not, then that party's process will simply halt forever (because it is waiting for the other parties to call `get_plain_text()` as well).

### ISSUE THREAD

**Issue by Wuliaxue** [facebookresearch/CrypTen#374]
The `get_plain_text()` function essentially performs an all-reduce on the relevant tensor. This requires all the processes (except the TTP, if it exists) to participate in the communication, that is, all parties must agree to share their secret share of the tensor. If one party calls `get_plain_text()` but the other parties do not, then that party's process will simply halt forever (because it is waiting for the other parties to call `get_plain_text()` as well).

_Originally posted by @lvdmaaten in https://github.com/facebookresearch/CrypTen/issues/233#issuecomment-803428054_
Hello!Could you give me a simple example in codes to proof that when only one process uses get_plain_text(),that process will halt forever?Please

**Comment by gcormode** [comment]
I believe that this is the intended behavior.  Do you have a concern with this scenario?

**Comment by lvdmaaten** [comment]
This is intended behavior. If one of the parties refuses to reveal their share, none of the parties will get access to the shared secret. This is the correct behavior for the threat model implemented in CrypTen.

**Comment by Wuliaxue** [comment]
> This is intended behavior. If one of the parties refuses to reveal their share, none of the parties will get access to the shared secret. This is the correct behavior for the threat model implemented in CrypTen.

Suppose there is a server where two clients upload secrets to the server for calculation. The server cannot obtain the real data of the client but can obtain the real results after calculation. Do you think this scenario can be implemented with Crypten？

**Comment by knottb** [comment]
If the two clients each have values they would like to encrypt and perform computations on, they should each contribute their data via crypten and perform computations in crypten. The server can then participate in this quorum as well and the result can be revealed to the server by using a `reduce` rather than `all_reduce` operation. This can be done using the `dst` kwarg inside of `get_plain_text()`:

```
# Define client / server ranks for reference
CLIENT_X = 0
CLIENT_Y = 1
SERVER = 2

# Encrypt data from each source
x_enc = crypten.cryptensor(client_x_data, src=CLIENT_X)
y_enc = crypten.cryptensor(client_y_data, src=CLIENT_Y)

# Perform computation
z_enc = function_to_perform_in_crypten(x_enc, y_enc)

# Clients will receive None
z = z_enc.get_plain_text(dst=SERVER)
```

**Comment by Wuliaxue** [comment]
> 

Yes,secure MPC just want party B to obtain party A's shared secret to excute calculation,but the B can get A's real data by performing get_plain_text(), which is against the principle of MPC.Like the classic secure two-party calculation protocol known as the Yao millionaire problem, both sides can draw conclusions about who is richer without knowing each other's true wealth.
