### ISSUE TITLE
[Question] Training on private data

### ISSUE THREAD

**Issue by mo-zahran** [facebookresearch/CrypTen#38]
First, I would like to thank you for the fantastic and well-structured tutorials.
I have a question about a security use case, but I don’t know the technical term of it.
```
Alice wants to train a simple neural network on MNIST data. 
But Bob has all the labels needed for training, and he will not share it. 
Can Alice train his model on the encrypted data from Bob and How?
```

**Comment by knottb** [comment]
Hi,

The example you gave seems very similar to the Data Labeling example in tutorial 3 (Scenario 1). See box [6] here: https://github.com/facebookresearch/CrypTen/blob/master/tutorials/Tutorial_3_Introduction_to_Access_Control.ipynb

**Comment by mo-zahran** [comment]
Thanks @knottb.
