### ISSUE TITLE
module 'torch._C' has no attribute 'HalfStorageBase'

### ISSUE THREAD

**Issue by DrDavidS** [facebookresearch/CrypTen#383]
##  Feature
```python
import torch
import crypten
```

it raise:
AttributeError: module 'torch._C' has no attribute 'HalfStorageBase'

MacOS
python = 3.7.13
torch = 1.11.0
crypten = lastest

## Alternatives

see: https://stackoverflow.com/questions/71581572/attributeerror-module-torch-c-has-no-attribute-halfstoragebase

**Comment by knottb** [comment]
This is fixed in the latest version - note that the version on pip is not up-to-date. To update, download the codebase from github and `pip install -e <path-to-crypten-folder>`.

The issue code is updated here: https://github.com/facebookresearch/CrypTen/blob/main/crypten/common/serial.py#L98-L105
