### ISSUE TITLE
How could we save a crypten model trained by encrypted data

### ISSUE THREAD

**Issue by quwenjie** [facebookresearch/CrypTen#385]
Here I have a question about how we could save a crypten model to binary trained like in Tutorial 7?
I tried to use crypten.save to save the model state dict and then use crypten.load to load the state dict, but the names don't match.

**Comment by jessijzhao** [comment]
I am unable to reproduce your issue by adding the following code snippet after cell 7 in Tutorial 7:
```
import io

# save encrypted model's state_dict
f = io.BytesIO()
crypten.save(model.state_dict(), f)
f.seek(0)

# load encrypted model's state_dict and check that the keys are the same
assert(crypten.load(f).keys() == model.state_dict().keys())
```

Could you describe what you are doing in more detail?
