### ISSUE TITLE
when I run Tutorial_1_Basics_of_CrypTen_Tensors:'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by YZY010203** [facebookresearch/CrypTen#387]
sometimes it runs correct and sometimes it error like this.

![2022-06-18 17-50-26 的屏幕截图](https://user-images.githubusercontent.com/63569612/174433049-513de7db-941c-45aa-8a6b-b5de7c1d90c5.png)
![2022-06-18 17-50-40 的屏幕截图](https://user-images.githubusercontent.com/63569612/174433056-3d302f49-3932-4385-ae57-b5840549ba8b.png)

**Comment by lvdmaaten** [comment]
Can you provide a minimal repro for this issue? This seems to be the same issue as https://github.com/facebookresearch/CrypTen/issues/395, which I cannot reproduce on my end.
