### ISSUE TITLE
mpc.run_multiprocess decorated functions can't return a torch tensor

### ISSUE THREAD

**Issue by youben11** [facebookresearch/CrypTen#39]
Returning a torch.tensor from a run_multiprocess decorated function will throw `ConnectionRefusedError: [Errno 111] Connection refused`, I'm not sure why this happens with torch tensors and not other python objects, I guess pytorch requires processes to be still active to get tensors. Might be related to [this](https://github.com/pytorch/pytorch/issues/7181)

#### workspace information
```bash
$ python collect_env.py 
Collecting environment information...
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Manjaro Linux
GCC version: (GCC) 9.2.0
CMake version: version 3.16.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.0
[pip3] torch==1.3.1
[conda] torch                     1.3.0                    pypi_0    pypi
[conda] torchvision               0.4.1                    pypi_0    pypi
$
$ pip freeze
absl-py==0.9.0
astor==0.8.1
attrs==19.3.0
backcall==0.1.0
bleach==3.1.0
certifi==2019.11.28
chardet==3.0.4
Click==7.0
-e git+https://github.com/facebookresearch/CrypTen.git@693dd6cc9918e982963e6acc186215d0f0769080#egg=crypten
decorator==4.4.1
defusedxml==0.6.0
entrypoints==0.3
Flask==1.1.1
Flask-SocketIO==4.2.1
future==0.18.2
gast==0.2.2
google-pasta==0.1.8
grpcio==1.26.0
h5py==2.10.0
idna==2.8
importlib-metadata==1.3.0
ipykernel==5.1.3
ipython==7.10.2
ipython-genutils==0.2.0
ipywidgets==7.5.1
itsdangerous==1.1.0
jedi==0.15.1
Jinja2==2.10.3
joblib==0.14.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.0.0
jupyter-core==4.6.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
lz4==2.2.1
Markdown==3.1.1
MarkupSafe==1.1.1
mistune==0.8.4
more-itertools==8.0.2
msgpack==0.6.2
nbconvert==5.6.1
nbformat==4.4.0
notebook==6.0.2
numpy==1.18.0
onnx==1.6.0
opt-einsum==3.1.0
pandocfilters==1.4.2
parso==0.5.2
pexpect==4.7.0
phe==1.4.0
pickleshare==0.7.5
Pillow==6.2.1
prometheus-client==0.7.1
prompt-toolkit==2.0.9
protobuf==3.11.2
ptyprocess==0.6.0
Pygments==2.5.2
pyrsistent==0.15.6
python-dateutil==2.8.1
python-engineio==3.11.1
python-socketio==4.4.0
PyYAML==5.2
pyzmq==18.1.0
qtconsole==4.6.0
requests==2.22.0
scikit-learn==0.22
scipy==1.4.1
Send2Trash==1.5.0
six==1.13.0
sklearn==0.0
-e git+git@github.com:youben11/PySyft.git@477be2e677127b924d5968bcb51fe87e3017912a#egg=syft
syft-proto==0.1.0a1.post36
tblib==1.6.0
tensorboard==1.15.0
tensorflow==1.15.0
tensorflow-estimator==1.15.1
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
tf-encrypted==0.5.9
torch==1.3.0
torchvision==0.4.1
tornado==6.0.3
traitlets==4.3.3
typing-extensions==3.7.4.1
urllib3==1.25.7
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.56.0
websockets==8.1
Werkzeug==0.16.0
widgetsnbextension==3.5.1
wrapt==1.11.2
zipp==0.6.0
zstd==1.4.3.2

**Comment by knottb** [comment]
Closing as this appears to be working.

**Comment by anonauthors01001** [comment]
This issue still persists today. Whether I'm returning an encrypted or unencrypted tensor - I get a connection refused error. Not returning a value, or returning something else works

Code:

#import the libraries
import crypten
import torch
# import logging
# logging.basicConfig(level=logging.DEBUG)

#initialize crypten
crypten.init()
#Disables OpenMP threads -- needed by @mpc.run_multiprocess which uses fork
torch.set_num_threads(1)

## Try to run matrix mult

import crypten.mpc as mpc
import crypten.communicator as comm

@mpc.run_multiprocess(world_size=2)
def matrix_mult(mat1_enc, mat2_enc):

    ## Debug stuff
    rank = comm.get().get_rank()
    crypten.print(f"\nRank {rank}:\n {mat1_enc}\n{mat2_enc}\n", in_order=True)

    out_enc = mat1_enc.matmul(mat2_enc)
    # return out_enc.get_plain_text()
    return out_enc


matrix_size = 10
A = torch.randn(matrix_size, matrix_size)
B = torch.randn(matrix_size, matrix_size)
A_enc = crypten.cryptensor(A, ptype=crypten.mpc.arithmetic)
B_enc = crypten.cryptensor(B, ptype=crypten.mpc.arithmetic)
C = matrix_mult(A_enc, B_enc)

print(C)
