### ISSUE TITLE
Whether to support python3.6.5

### ISSUE THREAD

**Issue by Averryjj** [facebookresearch/CrypTen#394]
Crypten can it be installed and run in the environment of python3.6.5?

**Comment by lvdmaaten** [comment]
CrypTen requires Python 3.7 or higher for compatibility with the latest ONNX. If you are not planning to import/export CrypTen graphs, you could update the Python version in `env.yml` to 3.6, remove `onnx` from the `requirements.txt`. and remove all the `import onnx` statements in the CrypTen code if you truly have to run on Python 3.6.
