### ISSUE TITLE
Why is the ReLU much faster than the linear layer?

### ISSUE THREAD

**Issue by hobbitlzy** [facebookresearch/CrypTen#397]
Hi, I am trying the `mpc_cifar` example. The two parties are on two nodes connected by the LAN.  I profile the `LeNet` and find the ReLU layers only take up around 20% of the inference time, which should have been the bottleneck in my understanding (learned from existing papers :D). Do you have any ideas about this?

**Comment by lvdmaaten** [comment]
The results probably depend a lot on the latency of your interconnect as well on where the compute is performed. 

Presuming you are using 16 bits of precision, evaluating a ReLU layer requires 5 rounds of communication. The matrix multiplication inside the linear layers takes one round of communication (see [Table 2 in Appendix B](https://arxiv.org/pdf/2109.00984.pdf)). 

If latency in your interconnect is low and the compute is done on CPU, I suppose it is possible that the relative time spent on ReLU is not that large. If your latency increases and compute is faster (that is, you are running on GPU), this number can shift a lot though. See [Figure 8](https://arxiv.org/pdf/2109.00984.pdf) for an illustration of this.
