### ISSUE TITLE
RuntimeError: result type Float can't be cast to the desired output type Long ERROR:root:One of the parties failed. Check past logs

### ISSUE THREAD

**Issue by dikjstra** [facebookresearch/CrypTen#404]
When running the example program in the tutorials folder the following error occurs:
RuntimeError: result type Float can't be cast to the desired output type Long
ERROR:root:One of the parties failed. Check past logs

How can I solve it please?

**Comment by lvdmaaten** [comment]
Can you provide a minimal repro so that I can try and reproduce this issue locally?

**Comment by dikjstra** [comment]
> Can you provide a minimal repro so that I can try and reproduce this issue locally?
Hello, yesterday I re-git cloned the latest source code, and now the problem has been solved, thank you!
