### ISSUE TITLE
How do I use Adam optimizer on Crypten encrypted training data

### ISSUE THREAD

**Issue by dikjstra** [facebookresearch/CrypTen#405]
I found out that CrypTen only provides SGD optimizer
How should I call the Adam optimizer provided by pytorch on encrypted data, thank you！

![QQ截图20220913170521](https://user-images.githubusercontent.com/90977053/189860409-4dce16cc-650c-46ed-83a1-9889008f03f7.png)

**Comment by lvdmaaten** [comment]
Right now, only SGD is implemented. You could implement an `Optimizer` akin to [this one](https://github.com/facebookresearch/CrypTen/blob/f4cbdfc685d9064f45a5654dee9f3809f6d93e7f/crypten/optim/sgd.py) for Adam. The implementation will be almost identical to the current implementation in PyTorch, with the exception that you'll have to introduce some `with crypten.no_grad:` blocks. Feel free to send a PR!

**Comment by dikjstra** [comment]
> 目前，只实施了 SGD。你可以为亚当实现一个`Optimizer`类似于[这个的。](https://github.com/facebookresearch/CrypTen/blob/f4cbdfc685d9064f45a5654dee9f3809f6d93e7f/crypten/optim/sgd.py)该实现几乎与 PyTorch 中的当前实现相同，只是您必须引入一些`with crypten.no_grad:`块。随意发送公关！

Thanks for your answer!

**Comment by dikjstra** [comment]
> Right now, only SGD is implemented. You could implement an `Optimizer` akin to [this one](https://github.com/facebookresearch/CrypTen/blob/f4cbdfc685d9064f45a5654dee9f3809f6d93e7f/crypten/optim/sgd.py) for Adam. The implementation will be almost identical to the current implementation in PyTorch, with the exception that you'll have to introduce some `with crypten.no_grad:` blocks. Feel free to send a PR!

Thanks for your answer!
