### ISSUE TITLE
The  problems of crypten in network communication

### ISSUE THREAD

**Issue by Averryjj** [facebookresearch/CrypTen#407]
![企业微信截图_1663590060396](https://user-images.githubusercontent.com/89241701/191018113-8d471148-4fd7-4140-a5ac-25059caee4b3.png)
Hi, I'm very interested in Crypten and working on it now. But I also met some problems and hope any ACE can help me answer them. In crypten.init() of rank1，the information about the network configuration of rank2 is not seen in the source code. May I ask the follows questions? 
(1)  During the calculation, does rank1 communicate with rank2 directly？
(2)  Or do they communicate indirectly by transferring the intermediate calculation results through the “rank0：master” node?
(3)  In the star network structure, is it feasible for “rank0：master” node as the proxy of forwarding the message? Namely，does Crypten support the star networks? How does it support?

**Comment by lvdmaaten** [comment]
To add to this: CrypTen relies on MPI collectives (broadcast, allreduce, etc.) for all communication. So parties communicate with each other directly, not via an intermediary rank-0 node in a star network. For the implementation of all this, we rely on `torch.distributed` so the ways to do the initial rendez-vous between parties [are the same as in PyTorch](https://pytorch.org/docs/stable/distributed.html#tcp-initialization). Depending on whether you do CPU or GPU computations, the backend used to implement the MPI collectives will change: Gloo for CPU and NCCL for GPU. 

If you wanted to implement a star network, perhaps the easiest thing to do would be to add a backend in PyTorch the implements the MPI collectives in that way and adopt that backend in CrypTen. This would certainly be less efficient that the ring implementation of collectives like allreduce that the current backends use though.
