### ISSUE TITLE
Can I modify the number of iterations to make the result of Div() or reciprocal() more accurate?

### ISSUE THREAD

**Issue by siqiliua** [facebookresearch/CrypTen#408]
I figure out that Div() or reciprocal()  is approximated by Newton-Raphson iterations. Can I modify the number of iterations to make the result of Div() or reciprocal() more accurate? If it is ok, how could I modify it ?

**Comment by lvdmaaten** [comment]
You can change the config variable [here](https://github.com/facebookresearch/CrypTen/blob/main/configs/default.yaml#L16). You can also use a `with` block to change the value temporarily:
```
with crypten.mpc.ConfigManager("reciprocal_nr_iters", nr_iters):
   ...
```
