### ISSUE TITLE
What if I want to perform a two-party calculation in a situation where three-party communication has already been established? It looks like you can only restart the service

### ISSUE THREAD

**Issue by mingo0117** [facebookresearch/CrypTen#409]
For help: I have initialized a three-party computing environment by setting environment variables (os.environ and crypten.init())，parameters just like: 
```
alice:
{
    "WORLD_SIZE": "3",
    "RANK": "0",  
    "RENDEZVOUS": "env://",
    "MASTER_ADDR": "192.168.173.173",
    "MASTER_PORT": "9003"
}
bob:
{
    "WORLD_SIZE": "3",
    "RANK": "1",  
    "RENDEZVOUS": "env://",
    "MASTER_ADDR": "192.168.173.173",
    "MASTER_PORT": "9003"
}
carol
{
    "WORLD_SIZE": "3",
    "RANK": "2",  
    "RENDEZVOUS": "env://",
    "MASTER_ADDR": "192.168.173.173",
    "MASTER_PORT": "9003"
}
```
It works. But now I want to use only Alice and Bob for the two-party operation, and it is clear that the original environment variables are no longer applicable. So what's the solution, other than restarting the service? I've tried crypten.uninit(), set two-party environment variables, just like: 
```
alice:
{
    "WORLD_SIZE": "2",
    "RANK": "0",  
    "RENDEZVOUS": "env://",
    "MASTER_ADDR": "192.168.173.173",
    "MASTER_PORT": "9004"
}
bob:
{
    "WORLD_SIZE": "2",
    "RANK": "1",  
    "RENDEZVOUS": "env://",
    "MASTER_ADDR": "192.168.173.173",
    "MASTER_PORT": "9004"
}
```
and crypten.init(), but it still doesn't work (crypten.init() blocks). 

Thx!

**Comment by mohammad-alrubaie** [comment]
Hello, 
Two quick ideas. Have you tried to run `crypten.uninit()` before changing the original environment variables, and `crypten.init()` after updating them? Also, have you issued crypten.uninit() from the rank 0 machine?

**Comment by lvdmaaten** [comment]
CrypTen assumes that all parties partake in all the computations and communication. You can `uninit` and `init` per @mohammad-alrubaie's suggestions but this is not very efficient: for example, it will cause PRZS seeds to always be reinitialized (which adds a round of communication) and re-does the rendezvous between parties.

I faced a similar problem recently and hacked up [this](https://gist.github.com/lvdmaaten/146287967853186b3296b86aa7d55504), which implements a `participating_parties` context manager. The code snippet does require https://github.com/facebookresearch/CrypTen/pull/393 to be merged. I hope this is helpful.

**Comment by lvdmaaten** [comment]
@mingo0117 Does this answer your question?

**Comment by mingo0117** [comment]
> @mingo0117 Does this answer your question?

Sorry, I was a little busy recently and forgot to reply. The problem has been solved. Thank you very much!
