### ISSUE TITLE
Training with crypten is slow

### ISSUE THREAD

**Issue by dikjstra** [facebookresearch/CrypTen#414]
Is it normal that training a model encrypted with encrypt on encrypted data is much slower than training the same model with pytorch using the same unencrypted data

**Comment by lvdmaaten** [comment]
Yes that is expected. See the CrypTen paper for details on expected slowdowns relative to plaintext training in PyTorch.

**Comment by dikjstra** [comment]
> Yes that is expected. See the CrypTen paper for details on expected slowdowns relative to plaintext training in PyTorch.

I read the paper today, thank you!
