### ISSUE TITLE
Training over Public Weights

### ISSUE THREAD

**Issue by rtaiello** [facebookresearch/CrypTen#415]
Hi All,

is it possible to train a Public Model over an encrypted dataset? In all the tutorials I found that also the model has to be encrypted, am I missing something? Thanks in advance!

**Comment by lvdmaaten** [comment]
It is possible to do this but you have to be very careful in how you handle with information leakage that stems from the fact that your model parameters (and therefore, your parameter gradients!) are public. In a worst-case scenario, your parameter gradients contain exactly your supposedly encrypted data -- implying your training algorithm does not protect the data at all. To still protect the data, you would typically compute encrypted gradients and apply a differentially private release mechanism (like in DP-SGD) to those gradients. Note that this gives you a different (weaker) security guarantee than full encrypted training though.

**Comment by rtaiello** [comment]
Many thanks @lvdmaaten for the clarification, is it available a code snippet in Crypten to do that?

**Comment by lvdmaaten** [comment]
No, but @yuansen23 [worked on this](https://eprint.iacr.org/2021/835) in the past so he may have some code for this?
