### ISSUE TITLE
Where does the modulo take when generating arithmetic shares?

### ISSUE THREAD

**Issue by hobbitlzy** [facebookresearch/CrypTen#416]
Hi, the paper writes the arithmetic share satisfies $x = \sum_{p \in P} [x]_{p} mod Q$. I find the [init method](https://github.com/facebookresearch/CrypTen/blob/efe8edad571be1c586d0d9cefc562d562d4e9aa1/crypten/mpc/primitives/arithmetic.py#L102) of class `ArithmeticSharedTensor` does not include the modulo Q. So, I am curious where does the modulo happen.

**Comment by lvdmaaten** [comment]
The `PRZS` method calls [this function](https://github.com/facebookresearch/CrypTen/blob/efe8edad571be1c586d0d9cefc562d562d4e9aa1/crypten/common/rng.py#L12) which contains an argument called `ring_size` that governs the value of Q.

In practice, the protocol use a ring size of 2**64 and so we rely on the 64-bit longs that we use "wrapping around" to implicitly perform the modulo operation for us.
