### ISSUE TITLE
MPC Protocols

### ISSUE THREAD

**Issue by Zeinab-Rahmani** [facebookresearch/CrypTen#428]
Hello. I would like to know what MPC protocols are implemented through Crypten? Could you please provide a link for me. 

Thank you.

**Comment by lvdmaaten** [comment]
See the [CrypTen paper](https://arxiv.org/pdf/2109.00984.pdf) for full details on the protocols implemented.

**Comment by Zeinab-Rahmani** [comment]
I studied the paper. However, I couldn't see the list of protocols that are implemented through Crypten. In section Related Work, I see some platforms that implemented SMC. But I Would like to know the protocols that are implemented by Crypten.

Thank you.

**Comment by lvdmaaten** [comment]
The appendix of the paper describes all the protocols and functions implemented in great detail, right?

**Comment by Zeinab-Rahmani** [comment]
Yes. I had another version of [this paper](https://proceedings.neurips.cc/paper/2021/file/2754518221cfbc8d25c13a06a4cb8421-Paper.pdf)  in which the appendix is not included. Thank you.
