### ISSUE TITLE
How to handle the errors of non-linear operators?

### ISSUE THREAD

**Issue by hobbitlzy** [facebookresearch/CrypTen#431]
I encounter extreme errors when using operators such as `exponential` and `inv_sqrt`. I find this is because my input is out of their 'safe intervals'. Can I fix this by changing the parameters of Crypten, such as the precision of the fixed-point encoder?

**Comment by lvdmaaten** [comment]
I would suggest changing configuration parameters like [this one](https://github.com/facebookresearch/CrypTen/blob/main/configs/default.yaml#L12) for exponential functions first. 

Alternatively, you could try and limit the magnitude in some other way. Even in 64-bit floating-point representations it is generally a bad idea to take an exponential of a number you don't control the range of, and one should try to use things like the [log-shift trick](https://timvieira.github.io/blog/post/2014/02/11/exp-normalize-trick/).
