### ISSUE TITLE
How to use smaller ring?

### ISSUE THREAD

**Issue by hobbitlzy** [facebookresearch/CrypTen#433]
Currently, the Crypten uses `torch.long` to define the tensors so that the ring size is $2^{64}$. I want to try smaller ring in my models. The problem is that I find the used `torch.long` is hardcoded and there is no convenient API to change this. Is there any suggestions for moving to smaller ring?

**Comment by mohammad-alrubaie** [comment]
As you already found, `torch.long` are assumed and hard-coded, and modulo 2<sup>64</sup> operations rely on `torch.long` behavior, so apart from changing `torch.long` to another data type, e.g. `torch.int`, wherever is needed, it may not be possible.

**Comment by hobbitlzy** [comment]
Thanks for your reply! I will try this. I want to use a smaller ring because this can reduce communication overhead. But I am not aware of the potential risks of such modification. Could you share whether you choose to use ring size $2^{64}$?

**Comment by mohammad-alrubaie** [comment]
You are right that decreasing the ring size would force you to decrease the precision (thus, scaling factor) to avoid errors in computation. See https://github.com/facebookresearch/CrypTen/issues/400 where for a small number of operations, it appears 29 bits of precision is adequate, but my guess that for more than one operation, we need to decrease the precision even lower, say 22 bits as Brian mentioned here: https://github.com/facebookresearch/CrypTen/issues/367
So, if you use a ring size of 32 bits, you will be forced to go much lower for precision, and that will introduce limitations to what you can do in terms of computation. While I wasn't involved in the original paper, I would say 64 bits ring was a good compromise between comm. cost and providing decent room for computation without the fear of errors. 
Notice that some operations like addition and XOR don't require communication, while some others do. Also, comparisons require changing the representation from arithmetic to binary which also needs communication. So, it may be useful to re-think your ML computation in that view to see if you can use operations or algorithms that could reduce communication regardless of ring size. That would also be a good type of research that CrypTen was meant to enable for ML practitioners (without needing to know much about the underlying secret sharing mechanisms). See the paper's experiment section on which operations cost the most for ideas on where to optimize.

**Comment by hobbitlzy** [comment]
Okay, see your points. Thanks😀.
