### ISSUE TITLE
Encrypted model, public data

### ISSUE THREAD

**Issue by SorourMo** [facebookresearch/CrypTen#435]
Hi,

Your tutorials show a scenario where Alice has her encrypted pretrained model, and Bob has his encrypted data. Training or inference can then be done with both components available. 

In my scenario, Bob's data isn't encrypted. Bob gets Alice's encrypted model along with the inference platform. Could Bob use Alice's encrypted model to infer from his own data (on his device)? Most of the time, this happens when inference is done on a user's device and the model owner wants to protect the weights/structure of the pretrained model. Since the inference is done on the user's device, the data is not required to be encrypted. How Crypten can be used in this case?

Thanks,

**Comment by mohammad-alrubaie** [comment]
To the best of my knowledge, it can't be done. CrypTen relies on additive secret sharing to "encrypt" the data. With that, Alice's model parameters are secret shared with Bob, and Bob's data is secret shared with Alice. This means that each parameter from Alice's model is split into two additive shares, one is kept with Alice, say `a0`, and the other with Bob, say `a1`, with `a0 + a1 = a the original model parameter). Similar thing for any feature in any feature vector held by Bob. 
Hence, with CrypTen, you can't really transport the model encrypted to Bob as the requirement is that its shares are held between Alice and Bob. With that, it's understandable that even inference would still require some communication between Alice and Bob. 
Separately, assume the model was encrypted using fully-homomorphic encryption (FHE) with Alice's public key. You can naturally send the encrypted model to Bob, and they would be able to do inference, but even in this case, Alice may need to decrypt the output (you can still protect the true output with some masking). However, CrypTen doesn't support FHE at the moment. So, user <=> server communication would be needed for CrypTen.

**Comment by lvdmaaten** [comment]
@mohammad-alrubaie summarized it really well.

Note that Alice and Bob can compute predictions on Bob's unencrypted data but Alice needs to be involved in the computations though. Basically, the first step in the computation would be to encrypt Bob's data (although this may only happen after the first layer of the model is evaluated). The resulting prediction will thus be encrypted; it has to be because the prediction may leak information about the model weights, and the entire point of CrypTen is that model weights cannot leak in any way.

**Comment by SorourMo** [comment]
Thank you @mohammad-alrubaie  and @lvdmaaten 
It makes sense.

>The resulting prediction will thus be encrypted; it has to be because the prediction may leak information about the model weights

@lvdmaaten  Do you mean in general or when Crypten is used for inference? I cannot see why the output of a model would leak information about the model weights. Could you please elaborate a little bit?

**Comment by SorourMo** [comment]
That's correct. Thanks.
