### ISSUE TITLE
Why not transform the truncation of a public value by multiplication of its reciprocal?

### ISSUE THREAD

**Issue by hobbitlzy** [facebookresearch/CrypTen#439]
Hi, I read the appendix of the paper of the Crypten. The Appendix writes dividing a public value may lead to a wrong result due to wrapping around the ring. But if the value is public, parties can compute its reciprocal and then multiply to it. If I understand correctly, multiplication is both cheap and accurate than truncation. So why the public truncation is necessary?

**Comment by gcormode** [comment]
Hi, 
Computing the reciprocal of a value is still a division, and subject to the same issues about its representation in a ring.   So while the multiplication operation is indeed cheap and usually accurate (provided values remain within the ring), the reciprocation step has all the same issues as division.

**Comment by hobbitlzy** [comment]
Since the public value is pre-known, can parties compute its reciprocal offline and save it for the online stage?

**Comment by gcormode** [comment]
The parties could certainly compute the reciprocal offline, but that would not change the concern raised in the appendix of the crypten paper (Truncation, in Section A.1.1 of https://lvdmaaten.github.io/publications/papers/crypten.pdf ): whether you use division, or multiplication by the reciprocal, there will still be issues of "wrap around" for shares represented as values from a ring.  Pre-computation might affect the computational cost of the operation, but will not affect the ability to interpret the result correctly.

**Comment by hobbitlzy** [comment]
Understand. Thanks for your reply.
