### ISSUE TITLE
Can a quantum neural network be used for classification?

### ISSUE THREAD

**Issue by sauravtii** [facebookresearch/CrypTen#440]
Hi,

I was referring to this [tutorial](https://github.com/facebookresearch/CrypTen/blob/main/tutorials/Tutorial_4_Classification_with_Encrypted_Neural_Networks.ipynb) and wanted to ask whether is it possible to do the same thing using a quantum neural network model (using [torchquantum](https://github.com/mit-han-lab/torchquantum)) instead of a classical one?

If yes, what should be the necessary changes?

**Comment by gcormode** [comment]
Hi, 
Crypten is designed to work with training "classical" models, and is not focused on quantum models.  You are welcome to try extending it to handle quantum networks for yourself with no guarantees :-)
