### ISSUE TITLE
'mpc_imagenet' returns strange accuracy.

### ISSUE THREAD

**Issue by hobbitlzy** [facebookresearch/CrypTen#443]
I tried the 'mpc_imagenet' example. The printed accuracy is 1/n, where n is the number of samples. I have tried to remove all the encryption and the results on the plain model are the same. The only change is the line of loading data. Is there something wrong?

**Comment by mohammad-alrubaie** [comment]
Are you defining the location of the dataset using the argument `--imagenet_folder` or some other way?
If passing the imagenet folder using the above command doesn't help, can you please share the changed line for loading data.

**Comment by hobbitlzy** [comment]
Thanks for your tips. I finally get the expected results using self-written scripts.
