### ISSUE TITLE
Where to get the codes of the three Benchmarks in the paper

### ISSUE THREAD

**Issue by zewen-s** [facebookresearch/CrypTen#460]
Three Benchmarks are introduced in the paper(CRYPTEN : Secure Multi-Party Computation Meets Machine Learning).In the paper it is mentioned that the code is available on   https://crypten.ai.  But I can't find it on  https://crypten.ai.  Could someone help me find the codes of the three Benchmarks.especially the codes that runs on the gpu.it would be very appreciated。

**Comment by lvdmaaten** [comment]
We have been unable to release the code for those benchmarks because that code is tied into Meta-internal systems (for data loading, _etc._). Really sorry!

**Comment by zewen-s** [comment]
Thank you very much for your answer.
