### ISSUE TITLE
How to access the coummnication datasize and the rounds.

### ISSUE THREAD

**Issue by hobbitlzy** [facebookresearch/CrypTen#462]
I notice the communication datasize and the rounds reported in yourpaper `CRYPTEN : Secure Multi-Party Computation Meets Machine Learning`. But I don't find a way to summarize them in the repo. Could you please help with this function?

**Comment by lvdmaaten** [comment]
You can use [these functions](https://github.com/facebookresearch/CrypTen/blob/main/crypten/communicator/communicator.py#L106-L141) to get the statistics you need.
