### ISSUE TITLE
How to collect the communication costs in CrypTen?

### ISSUE THREAD

**Issue by zkya** [facebookresearch/CrypTen#471]
Following the guidance,  the functions reset_communication_stats() and get_communication_stats() is executed. However, we found  that the communication costs is 0.  Hence, how to collect the communication costs correctly?
I am very much looking forward to your reply.

**Comment by lvdmaaten** [comment]
Can you post a minimal repro? Are you sure you are using the `DistributedCommunicator`? The `InProcessCommunicator` only passes references around and, for that reason, it is expected it'll only return 0. If you wanted to change this, you could decorate the relevant functions in `InProcessCommunicator` with the `@_logging` decorator in the same as is done in the `DistributedCommunicator`.

**Comment by zkya** [comment]
> Can you post a minimal repro? Are you sure you are using the `DistributedCommunicator`? The `InProcessCommunicator` only passes references around and, for that reason, it is expected it'll only return 0. If you wanted to change this, you could decorate the relevant functions in `InProcessCommunicator` with the `@_logging` decorator in the same as is done in the `DistributedCommunicator`.

For convenience,  we import run_multiprocess decorator from crypten.mpc to execute. 
@mpc.run_multiprocess(world_size=2)
def test_comm():
    comm.get().reset_communication_stats()
    if comm.get().get_rank() == 0:
        k = [2,5]
        comm.get().send_obj(k, BOB)
    if comm.get().get_rank() == 1:
        k = comm.get().recv_obj(ALICE)
    print(comm.get().get_communication_stats())

Thanks a lot.

**Comment by lvdmaaten** [comment]
Yeah, so you are using the `InProcessCommunicator` under the hood. Which means this is expected behavior. You want work around it if you want by adding `@_logging` decorators to the relevant `InProcessCommunicator` function (see the `DistributedCommunicator` implementation for an example).
