### ISSUE TITLE
Why log function implement in this way?

### ISSUE THREAD

**Issue by deadlywing** [facebookresearch/CrypTen#475]
I read the paper of crypten recently, and find that householder method is used for log function. But I am confused that it's an algorithm of finding root. Maybe we should construct a magic function `f(y)` so that` log(x)` is the root?

Besides, I read the paper cited by crypten for householder method, I want to know indeed which algo crypten adopts in code.

Is it algo2.4?
![image](https://github.com/facebookresearch/CrypTen/assets/25818621/d072653a-e1e9-4d15-b7f7-5e40c0099eb3)

Thanks.

**Comment by lvdmaaten** [comment]
See Appendix C.2.4 of the [CrypTen paper](https://arxiv.org/pdf/2109.00984.pdf) for details on the protocol implemented. The implementation is [here](https://github.com/facebookresearch/CrypTen/blob/6ef151101668591bcfb2bbf7e7ebd39ab6db0413/crypten/common/functions/approximations.py#L55).
