### ISSUE TITLE
Questions about CrypTen usage for training task outsourcing 

### ISSUE THREAD

**Issue by kejie7243** [facebookresearch/CrypTen#479]
Hello folks,

First, really appreciate for your excellent work and it is so inspiring and helpful! As a layman of security / MPC, I am wondering if I could use CrypTen to encrypt my data and model, then, I would send the encrypt data and model to a person with GPU and ask him for finish the training. Is there any security concern for this? Under this case, there is only one party involving in this task, the training speed should only be affected by the mapping of integer to floats? 

Again, thanks a lot for your great work and pardon me for the dummy questions. Have a nice day :)

**Comment by kejie7243** [comment]
@kwmaeng91 Thanks Kiwan for the great response. My motivation is simply like the example in the paper

```python
## In my side, I would encrypt the data
input_enc =  crypten.cryptensor(input, src=0)
label_enc = crypten.cryptensor(label, src=0)
model_enc = model.encrypt()

## Send the input_enc,  input_enc and model_enc to another person and he could update the model as:
output_enc = model_enc(input_enc)
model_enc.zero_grad()
loss_enc = criterion(output_enc , label_enc) loss_enc.backward()
optimizer.step() 
``` 

Does the above not work? Thanks again for your help!!!

**Comment by kwmaeng91** [comment]
Great that you figured it out! If your question is solved maybe you can close the issue?
