### ISSUE TITLE
Trusted first party

### ISSUE THREAD

**Issue by jimouris** [facebookresearch/CrypTen#505]
Hello! In [tfp_provider](https://github.com/facebookresearch/CrypTen/blob/main/crypten/mpc/provider/tfp_provider.py) you have a trusted first party for generating triples. What is the purpose of this file and how is this different from a trusted third party?

Thanks,
Dimitris

**Comment by gcormode** [comment]
Trusted First Party is a weaker security model for developing/testing under.  See the discussion at [https://github.com/facebookresearch/CrypTen/issues/450](https://github.com/facebookresearch/CrypTen/issues/450 
)

**Comment by jimouris** [comment]
Thanks @gcormode!
