### ISSUE TITLE
FixedPointEncoder.decode() produces incorrect results

### ISSUE THREAD

**Issue by tshead2** [facebookresearch/CrypTen#57]
The fixed point encoder produces correct results when round-tripping small integers:

```
>>> import crypten
>>> crypten.init()
>>> def round_trip(input):
...   encoder = crypten.encoder.FixedPointEncoder()
...   output = int(encoder.decode(encoder.encode(input)))
...   print(input, output, input - output)
... 
>>> round_trip(1)
1 1 0
>>> round_trip(13)
13 13 0
>>> round_trip(254)
254 254 0
>>> round_trip(2**16)
65536 65536 0
>>> round_trip(2**16 + 1)
65537 65537 0
```

However, larger values don't always produce correct results:

```
>>> round_trip(2**24)
16777216 16777216 0
>>> round_trip(2**24 + 1)
16777217 16777216 1                   <-- Wrong!
>>> round_trip(2**24 + 2)
16777218 16777218 0
>>> round_trip(2**24 + 3)
16777219 16777220 -1                  <-- Wrong!
>>> round_trip(2**47 - 2)
140737488355326 140737488355328 -2    <-- Wrong!
>>> round_trip(2**47 - 1)
140737488355327 140737488355328 -1    <-- Wrong!

```

Since the encoder reserves 16 bits for fractions, I would expect any integer in the range [-2^47, +2^47) to be encoded and decoded without change.

Looking at the implementation of FixedPointEncoder.encode(), I see that values are simply multiplied by the scale factor (2^16 by default) as you'd expect.  However, the implementation of decode() is (I think) doing much more than it should - seems like it should simply divide by the scale factor.  If I simplify the implementation to do just that, then I get the expected results.

Can you comment on the implementation of decode()?

Many thanks,
Tim

**Comment by knottb** [comment]
Hi Tim,

The issue here is an artifact of converting between float and long types. E.g. the following two code snippets are off by the same amount:

```
>>> round_trip(2**47 - 2)
140737488355326 140737488355328 -2 
>>> round_trip(2**47 - 1)
140737488355327 140737488355328 -1    
``` 

```
>>> torch.LongTensor([2**47 - 2]).float().long()
tensor([140737488355328])
>>> torch.LongTensor([2**47 - 1]).float().long()
tensor([140737488355328])
```

The precision of floating point numbers is not enough to capture the least significant digits in the given long values. We compute the remainder in our current `decode` step in order to ensure we don't reduce precision in our casting (long to float). However, we may not need to compute the remainder as our return value may be losing this precision anyway. We are investigating this now.

**Comment by tshead2** [comment]
The effect of a conversion to `float` makes sense; in my testing with a simplified `decode` implementation, I used double as a matter of habit, which explains why it produces exact results.  I think my project will have to get a better handle on our requirements for precision.  In the meantime we can patch `decode` if necessary.

Many thanks for the quick response, will be interested in the outcome of your investigation.

Cheers,
Tim

**Comment by shubho** [comment]
I think a 128 bit integer type would be ideal but such a thing does not exist in a performant way

**Comment by tshead2** [comment]
The more I think about it, the more I think that converting from LongTensor (int64) to float (float32) is an odd choice.  Consider this a strongly worded vote for double :)

Cheers,
Tim

**Comment by knottb** [comment]
The reason we chose to decode to float (float32) is because we want using CrypTen to be as similar as possible to using PyTorch. As far as I'm aware, most ML pipelines in PyTorch are implemented using 32-bit floating point values. By default our pipelines decrypt to 32-bit floats to integrate seamlessly into PyTorch pipelines.

We could potentially add a kwarg in the decoder to accept a dtype if it would be useful to keep from losing this precision.

**Comment by tshead2** [comment]
I'd suggest API allowing library users to specify the encoder to use when constructing encrypted tensors.  Our project is already using a custom communicator, and this would be comparable. 

Cheers,
Tim

**Comment by knottb** [comment]
Hi Tim,

I submitted the diff above regarding this issue. However, the protocols used to perform arithmetic do currently assume that encoded values can be added, subtracted, multiplied, and divided and that the encoder has certain properties (`precision_bits` kwarg in `__init__` and `_scale` attribute).

It is also required by the cryptographic protocols used that the encoding is isomorphic to integers. I'm curious, what is the encoder you are interested in using?

**Comment by tshead2** [comment]
@knottb - many thanks for that.  It's not that we're really passionate about encodings, we are debugging an experiment where the precision lost in the encoding round-trip came up as a potential source of problems, and we aren't implementing a "typical" PyTorch algorithm.  It's likely that we will want fine-grained control over the precision and behavior of the encoding, so the suggestion to allow user-supplied encoders was just to avoid hitting you with requests for an ad-hoc collection of features / kwargs.

Cheers,
Tim

**Comment by knottb** [comment]
Understood. For now, we may just expose a `dtype` parameter in the encoder / `get_plain_text()` function so you can specify `torch.double` for more precision. Additionally, you can increase the input precision by using `crypten.encoder.set_default_precision(bits)`. This can also be a significant source of precision loss, however there can be significant drawbacks to increasing the precision too much.
