### ISSUE TITLE
About secret-sharing in Tutorial 2

### ISSUE THREAD

**Issue by xiaobing0** [facebookresearch/CrypTen#67]
for example,
x_enc = crypten.cryptensor([1, 2, 3]), the x_enc is generated bu secret-sharinig, so it nedd at least two soruce, but the code
x_enc = crypten.cryptensor(x, src=i)
how the only one source i could complete encrype?

**Comment by knottb** [comment]
The `src` keyword argument refers to the source of the input data. For example, say we have two parties (Party 0 - Holds data, Party 1 - Does not hold data).

Consider the following code:

```
if comm.get().get_rank() == 0:
    x = torch.tensor([1, 2, 3])
else:
    x = torch.tensor([0, 0, 0])

x_enc = crypten.cryptensor(x, src=i)
```

Here, party 0 holds the tensor `x = torch.tensor([1, 2, 3])`, while party 1 holds the tensor `x = torch.tensor([0, 0, 0])`. If the source `src=i` uses `i == 0`, then when we decrypt `x_enc`, the result will be `torch.tensor([1, 2, 3])`. However, if the source uses `i == 1`, then the result will be `torch.tensor([0, 0, 0])`.

Please let us know if you have further questions.

**Comment by meryemJanatiIdrissi** [comment]
Hello
I have the same question as @xiaobing0  and I did understand the answer however it did not answer my question.

`# Create torch tensor
x = torch.tensor([1.0, 2.0, 3.0])

# Encrypt x
x_enc = crypten.cryptensor(x)`

For example, how can we complete the encryption in example above if there is one source?
can someone please explain it to me?

**Comment by MissiontoMars** [comment]
Maybe the issue explains the problem: https://github.com/facebookresearch/CrypTen/issues/188 @meryemJanatiIdrissi
